### ISSUE TITLE
support long species lists

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#1]
Moved from AtlasOfLivingAustralia/spatial-portal#135

biocache has a limit on the number of OR terms in a query. Species lists can exceed this limitation. 

For each possible usage of a species list, multiple biocache queries must be constructed and where used the results must be collated.

**Comment by nickdos** [comment]
I thought this was set by the `maxBooleanClauses` setting. The default is 1024 but we can increase it. The other issue is if the request is being sent to SOLR via GET, in which case you will hit a limit. So sending as POST is the better way to do this.

**Comment by adam-collins** [comment]
I'm not certain if increasing the limit is the way to go e.g. http://lists.ala.org.au/speciesListItem/list/dr652 has almost 20000 items. I expect this will be a problem  for SOLR that is best handled with client side collation.

The GET issue is resolved with qids.

phylolink has a similar problem.

**Comment by adam-collins** [comment]
At the very least it would be useful for biocache-service to make available through a webservice the actual maxBooleanClauses value.

**Comment by adam-collins** [comment]
Use biocache-service dynamic field species_list. e.g. http://biocache.ala.org.au/ws/occurrences/search?q=species_list:dr366

Also fix the bug in biocache-service because it is not working.
