### ISSUE TITLE
Phlylogenetic trees not shown on dialog

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/spatial-hub#105]
steps to reproduce
Tools > phylogenetic diversity
The table in section "step 2. select phylogenetic trees" is empty.

**Comment by qifeng-bai** [comment]
https://phylolink.ala.org.au/phylo/getExpertTrees?noTreeText=true: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://spatial-beta.ala.org.au' is therefore not allowed access.

Working on it

**Comment by qifeng-bai** [comment]
Allow CORS on Nginx setting. 
Todo: fix ansible script, however, there is no nginx role in Phlylink script

**Comment by temi** [comment]
@qifeng-bai webserver is the role used in phylolink which selects nginx using a variable.
