### ISSUE TITLE
Failed requests to postAreaWkt return HTTP 200 and spatial-hub does not show an error message

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#112]
**Describe the bug**
Failed requests to ``https://nectar-spatial-staging.ala.org.au/portal/postAreaWkt`` when creating an ``Area`` return ``HTTP 200``, without the expected ``id`` attribute, instead including an ``error`` attribute. The incorrect processing of this response generates a subsequent call to ``https://nectar-spatial-staging.ala.org.au/ws/object/undefined``.

**To Reproduce**
1. Go to 'nectar-spatial-staging' (its Postgres/Geoserver is triggering the error sequence)
2. Click on 'Add to Map'
3. Click on 'Area'
4. Click on 'Draw bounding box'
5. Click on 'Next'
6. Draw the area and click on 'Next'. If the bug is occurring, nothing happens at this point 

**Expected behavior**
* [ ] There should be an error displayed when ``/portal/postAreaWkt`` fails. 
* [ ] There should be an ``HTTP 5xx`` code when ``/portal/postAreaWkt`` fails.
* [ ] The javascript should not ignore the missing ``id`` in the result from ``/portal/postAreaWkt`` and should never attempt to resolve ``/ws/object/undefined``

**Actual behavior**
After seeing nothing happen in the interface when the call to Viewing using developer tools reveals an ``HTTP 200`` response to ``portal/postAreaWkt`` with an ``error`` attribute inside:

```json
{
    "error": "Unexpected error. Please notify support@ala.org.au."
}
```

There is a subsequent incorrect call to ``/ws/object/undefined`` because the javascript code is not correctly recognising the error and javascript is compensating for the lack of an ``id`` attribute by substituting ``undefined`` instead of an id, possibly due to the ``HTTP 200`` response code.

**Screenshots**
![screen shot 2018-07-03 at 10 32 06 am](https://user-images.githubusercontent.com/82365/42192679-b08cd5f4-7ead-11e8-9d32-9d5af7f91ba2.png)
![screen shot 2018-07-03 at 10 42 38 am](https://user-images.githubusercontent.com/82365/42192706-dcd69bd6-7ead-11e8-878b-1401d7eccb93.png)

**Additional context**
The Postgres/Geoserver on ``aws-spatial-prod`` doesn't appear to show the underlying problem causing ``/portal/postAreaWkt`` to fail and it is intermittent on ``nectar-spatial-staging``.

**Comment by qifeng-bai** [comment]
From Adam Collins: 
when there is a problem with creating areas on nectar-spatial-staging, try
SELECT setval('objects_id_seq', cast((select max(to_number(pid,'9999999999999'))+1 from objects) as bigint));

SELECT setval('objects_id_seq', cast((select max(to_number(pid,'9999999999999'))+1 from objects) as bigint));
