### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#126]
**Is your feature request related to a problem? Please describe.**
When external webservice is down, e.g. SOLR, there is no indication for the user when things don't work.

**Describe the solution you'd like**
There should be some notification of a failure, e.g. "some services are unavailable so some functions will not work" 

**Describe alternatives you've considered**
A new map panel that contains something like "biocache - unavailable, spatial-service - unavailable, sandbox - unavailable" when there is a problem. This status can be provided by PortalController.ping

All functions could be mapped to dependant services and appropriately disabled in the UI until PortalController.ping indicates that the service is again available.

Improving spatial-service process error messages is also required. Error messages should be consistent between spatial-hub and spatial-service.

**Notification of Error to Monitoring service**
When an error is detected, it should also send a notification of the failure to the monitoring service so that action can be taken to restore the failed service as soon as possible.  Idea is to not need to rely on the user to notify of the failure.

**Additional context**

**Tasks**
- [x] #134 
- [x] #135 
- [ ] #136 
- [x] #137 
- [x] #138

**Comment by Tasilee** [comment]
What is the status of this @adam-collins ?

**Comment by adam-collins** [comment]
Sufficient in 0.3.2
