### ISSUE TITLE
bug list 1

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#149]
List of issues from testing

* Add   to Map \| Species. If you select a species at step 1, then decide to   "Define new area" on Step 3, it removes the selected species. BTW:   Nice to see the checklist areas and animal tracks in step 2!
* You need to click on the   point layer for the legend to display. Probably should be displayed by   default, as usual?
* Left click on species   point on the map isn't generating the pop-up
* Add to Map \| Area \|   Select area from polygonal layer displays two copies of candidate layers.
* Add to Map \| Area Select   area from polygonal layer maps the selected layer but when you click on the   polygon, you get the layer classes displayed in legend, but not the layer   itself (probably doesn't need to but then why display the legend classes?) or   the selected area. That is, the area polygon isn't generated/mapped. The   place marker remains on the map.
* Add to Map \| Gazetteer   polygon. No dynamic landcover classes? The dynamic landcover layer maps ok.
* Add to Map \| Area \|   Current extent - seems to take a long while to map. I had the dynamic   landcover already mapped BTW.
* Add to Map \| Area \|   Environmental envelope - just zooms out maybe 10% and stops, clearing all   layers (I presume a fresh restart!?) with no pop-up dialog box. Tried 3   times, same result.
* Add to Map \| Facet \|   CAPAD Terrestrial 2014 showed individual polygons not the CAPAD   classification. As discussed. I guess this will apply across   multi-classification layers. Default: least categories :) I this case there   were 781 classes (polygon names) so paging through raises an issue. We   probably need a search mechanism as per legend. Vertical scroll bar seems   superfluous?
* Tools \| Area report -   interactive. Table obscures map as discussed.
* Tools \| Area report -   interactive. No endemic species? We need them in the report.
* Tools \| Area report -   PDF. Header on pop-up is still "Detailed Area report"
* Tools \| Scatterplot -   single. All steps pre-ticked.
* Tools \| Taxon frequency.   Header should be "Taxon frequency"
* Tools \| Taxon frequency.   "Year of start" should be "Start year for occurrences"
* Tools \| Taxon frequency.   Steps (3) and (4) should be swapped. That is we need to ask for the   "Target taxon" first
* Tools \| Taxon frequency.   Then we should ask about "Second taxon (ratio denominator)"
* Tools \| Tabulation.   CAPAD is using polygon names instead of classification. I guess this applies   to a range of layers.
* Tools \| Compare points.   Click on map for first point and beta effectively re-starts loosing current   layers. When I did this from scratch, it worked fine.
* Tools \| Compare points.   If you select three points, you can't see the third column. Horizontal scroll   bar not effective as far as I can see.
* Tools \| Compare points.   Not obvious how to remove the table as the only "Close" button is   at the bottom of the table. Also need at top.
* Tools \| Compare areas.   The file "comparison.csv" is confusing. Don't why I didn't pick   this up earlier. You have a column "Number of records" but you   don't know which area it applies to. Can't be both as one of the values is   "1" when it is both areas. Strongly suggest you simply use   "Number of occurrences - area 1" and "Number of occurrences -   area 2" rather than "found".
* Tools \| Compare areas.   Can you simplify by listing your ComparisonSummary.csv info at the bottom of   comparison.csv?
* Tools \| Generate points   doesn't seem to be working (small area).
* Tools \| Predict. Seems   to be working ok and the output files look good but while the prediction   layer is there, it is not actually mapped.
* Tools \| GDM. No output   layers produced and output table has no graph or images.
* Tools \| nearest   locality. Not working.
* Export \| Points isn't   kicking off the standard export functionality. Nothing exported.

**Comment by Tasilee** [comment]
Export | Points I just looked at and I am getting a consistent pattern. The first time I try an Export | Point sample, it simply generates a new beta window. That's it. If I re-try it, it works. I've now done that a few times. First hit doesn't work, subsequent in session ok.
