### ISSUE TITLE
Export layer resulted in error message

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#152]
> A user has reported this bug while using the beta version. See https://support.ehelp.edu.au/a/tickets/25711.
> 
> Hi,
> 
> FYI, I imported some data points in beta (which plotted fine), then tried to export layers. I got this twice.
> 
> Cheers,
> 
> Renee
> 
> > On 5 Dec 2018, at 11:58 am, support@ala.org.au wrote:
> > 
> > The download has failed. uniqueId:d099594a-e242-3996-9f82-0814bce4da12-1543971530014 path:/d099594a-e242-3996-9f82-0814bce4da12/1543971530014/records-2018-12-05.zip

**Comment by adam-collins** [comment]
This was a sandbox configuration issue causing offline downloads to fail.

* biocache-service config fixed download_dir, userdetails_url, download_url.
* ala-hub updated to 3.0.12 for the configurable mintDoi parameter.
