### ISSUE TITLE
Export map does not include points

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/spatial-hub#153]
**Describe the bug**
A simple map export (with occurrence points) to PNG or JPG fails to include the points.

**To Reproduce**
Steps to reproduce the behaviour:
1. biocache search results (occurrences) -> view interactive map (spatial portal)
2. Export menu at top left > Map
3. Choose jpg (or png) and hit Download
4. Map downloads without points.

**Expected behaviour**
Map downloads with points.

**Actual behaviour**
Map downloads without points.

**Comment by Tasilee** [comment]
Current issue remains on beta and Prod

**Comment by Tasilee** [comment]
Related to #162 but fixed in Chrome.
