### ISSUE TITLE
Add circle radius option to AOO and EOO (beta)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#163]
**Is your feature request related to a problem? Please describe.**
When thinking about how you could find what species were spatially associated with a target species, AOO is not ideal because the grid is generated from essentially an arbitrary origin - implying that points could be very close to the AOO boundary. This may limit associated species that may occur outside the AOO area and also include species that while inside the AOO area, are a grid size distance away.

**Describe the solution you'd like**
If we defined the area of interest as the area WITHIN a user-supplied radius to the location of the target species, we can be far more confident in generating a list of 'associated species'.

**Describe alternatives you've considered**
There are no more optimal solutions.

**Additional context**
AOO is the only strategy that can currently be used to identify species that are spatially associated with a target species (or even a target group of species) - and it is not as robust as I would like. The solution above is simple, and would provide a robust solution.

**Comment by adam-collins** [comment]
Add alpha hull and permit multiple alpha values. This will add the flexibility required.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/commit/485408efd0c1e43c9724695600fca50e6f6d58bf
