### ISSUE TITLE
POST /portal/ping failed due to size of body

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#173]
**Describe the bug**
An error in the nginx logs indicating a request failed due to the size of the HTTP POST body. It isn't clear from the name of the service why it would be accepting a body at all, given it sounds and looks from the logs like a simple Layer 7 KeepAlive request which are typically idempotent other than refreshing the session timeout.

**To Reproduce**
The error message in the log contains a URL which may or may not reproduce the error:
```
2019/03/13 09:11:38 [error] 9471#9471: *49346 client intended to send too large body: 45090911 bytes, client: [REDACTED], server: spatial.ala.org.au, request: "POST /portal/ping?sessionId=1552427766504 HTTP/1.1", host: "spatial.ala.org.au", referrer: "https://spatial.ala.org.au/?q=*:*&fq=geospatial_kosher:true&fq=species_group:Mammals&fq=state:%22New%20South%20Wales%22&lat=-28.4697&lon=152.8065&radius=10.0"
```

**Expected behavior**
If the post body was legitimate, we need to expand the size restrictions, otherwise need to determine why `/portal/ping` is sending large body requests.

**Actual behavior**
An error appeared in the logs. There are also other very similar errors at different times.

**Screenshots**

**Additional context**
Occurred on second day that `aws-spatial-prod` was CNAME'd to from `spatial.ala.org.au`.

**Comment by adam-collins** [comment]
Need to increase nginx post limit and reduce the size of data sent to /portal/ping.

**Comment by ansell** [comment]
I will increase the nginx post limit directly on the server. Which ansible inventory file should I modify to persist it in future?

**Comment by adam-collins** [comment]
ping refactored
