### ISSUE TITLE
Link to Spatial Portal Dashboard from User Profile not working

### ISSUE THREAD

**Issue by CorinnaPaeper** [AtlasOfLivingAustralia/spatial-hub#175]
The "Tabulate and graph all functions you've used in the Spatial Portal" link in the My Profile area returns a 404 error.

This link:

![Image1](https://user-images.githubusercontent.com/35747214/55531868-8c2a3d00-56f7-11e9-903f-63c143cd7170.png)

Returns this:
![Image2](https://user-images.githubusercontent.com/35747214/55531878-90eef100-56f7-11e9-8b9c-888ee2d9fefe.png)

**Comment by Tasilee** [comment]
Thanks Corinna. This is pointing back to the old SP and we need to finalize the logging associated with the new one ASAP: Adam is going to work on it.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ala-install/commit/a94fc91fb2e4af5046397173b17e4562ad2430a8

**Comment by ansell** [comment]
I am putting this on the Infrastructure Operations board because it requires userdetails to be redeployed

**Comment by ansell** [comment]
Verified this fix deployed to auth-test, so moving to Ready for CAB:

https://auth-test.ala.org.au/userdetails/myprofile

**Comment by Tasilee** [comment]
Tested ok 18/2/2020
