### ISSUE TITLE
Calls to biocache-service with fq=undefined

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#176]
There are calls from spatial portal users to biocache which include `fq=undefined`. These are then triggering calls to bie with `undefined` as a query parameter. This needs to be fixed in the spatial portal interface so that whatever is causing the `undefined` is isolated in javascript and doesn't attempt to call from that point on.

The following logs are from biocache-service:

```
==> /var/log/tomcat7/biocache-service.log <==
2019-04-08 15:11:00,751 [http-bio-127.0.0.1-8080-exec-16667] INFO au.org.ala.biocache.service.SpeciesLookupRestService  (SpeciesLookupRestService.java:396) - Requesting: https://bie.ala.org.au/ws/guid/batch?q=undefined

==> /var/log/nginx/access.log <==
[REDACTED] - - [08/Apr/2019:15:11:00 +1000] "GET /ws/webportal/wms/reflect?OUTLINE=false&&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&Q=qid%3A1554700260134&ENV=color%253A3366CC%253Bname%253Acircle%253Bsize%253A5%253Bopacity%253A1&CONTINUOUSWORLD=true&fq=undefined&SRS=EPSG%3A3857&BBOX=17532819.799940586,-7514065.628545966,20037508.342789244,-5009377.085697311 HTTP/1.1" 200 193 "https://spatial.ala.org.au/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "[REDACTED]" request_time=0.014 upstream_response_time=0.012 upstream_connect_time=0.000 upstream_header_time=0.012 upstream_cache_status=MISS
```

**Comment by qifeng-bai** [comment]
Issue may related to  line 347 makeMap function in AreaReportPDF
var fq is passed from line 268 getValue function
by checking the code, it may be caused by : line 95
 pages = (JSONArray) jp.parse(new String(getFileAsBytes("AreaReportDetails.json"), "UTF-8"));
Suspect that invalid fq or missing fq in that JSON
