### ISSUE TITLE
Search for CSDM ‘trusted’ datasets and import data into the SP

### ISSUE THREAD

**Issue by CorinnaPaeper** [AtlasOfLivingAustralia/spatial-hub#179]
CSDM user needs to be able to find and access published 'trusted' (CSDM) occurrence records/datasets via a new Search functionality across DOI’d data.

- DOI storage to be made searchable
- Trusted dataset to be discoverable by species, department/organisation, modeller, date (year?) [anything else?]
- Search only to return DOI’d datasets where the CSDM flag (or similar) in Metadata is set to TRUE
- Implement option to a) Import data to SP (see below), or b) send data to CSDM Modelling platform
- Data to be added to SP through:
     a)  Re-running of query [Phase 1]
    b) Using the stored .zip file [Phase 2]

**Comment by sat01a** [comment]
Sub tasks #215

**Comment by chrisala** [comment]
This issue represents a first cut of this feature, there are definitely improvements to be made.
