### ISSUE TITLE
Scatterplot requires better in/out adhoc point integration

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#18]
When mapping a scatterplot and a species layer the activity of removing various outliers is too complicated. This needs to be simplified.

**Comment by Tasilee** [comment]
Yep: Basically we need the same in/out point layer product based on highlighted points.

**Comment by Tasilee** [comment]
Playing: The current in/out option works well enough, if it didn't crash. Selected were three points from the scattertplot AND 26 points with missing (environmental) data
![capture](https://cloud.githubusercontent.com/assets/6656350/18262550/014b61a0-7446-11e6-8cb0-c9781e13ec30.jpg)

**Comment by Tasilee** [comment]
(This functionality will be used at the workshop on **September 28**)

**Comment by Tasilee** [comment]
This remains a bug. It is the selection of points with MISSING values that triggers the crash.

**Comment by Tasilee** [comment]
Bug remains

**Comment by adam-collins** [comment]
Issue moved to [AtlasOfLivingAustralia/spatial-portal #148](https://github.com/AtlasOfLivingAustralia/spatial-portal/issues/148) via [**ZenHub**](https://www.zenhub.com/)
