### ISSUE TITLE
Annotation of SP filtering steps and storage of Workflow steps

### ISSUE THREAD

**Issue by CorinnaPaeper** [AtlasOfLivingAustralia/spatial-hub#181]
[Project Requirement UR3]

CSDM user needs to be able to annotate all filtering steps taken, so that they are transparent and repeatable.

This is part of the ‘Publishing of CSDM dataset’ workflow (see UR4/GH#xxx)

- Pop-up window to capture:
    a) Annotation of all filtering steps (required)
    b) Generic annotation of dataset (optional)
- Filtering steps (including annotations?) to be captured in a SP Workflow Repository which gives an ID to each Workflow sequence to enable easier re-application of selected workflows to other datasets.
- Annotations and SP Workflow repository ID to be captured in Metadata.

**Comment by CorinnaPaeper** [comment]
Sub-tasks:

- #193 
- #194

**Comment by Tasilee** [comment]
The test workflow loads ok, and editing the title is ok as it is saved.

As previously noted on #194, the 'Annotations' are really 'Parameters' unless there is a more obvious way of adding an annotation to these parameters?

Editing an 'Annotation' doesn't seem possible anyway as any text typed in the box replaces what is there and renders the Parameters invalid?

It looks like any editing/replacement of 'Annotations' are auto-saved anyway so you can't 'back out' gracefully. Not good.
