### ISSUE TITLE
Model output layers and Area Reports

### ISSUE THREAD

**Issue by CorinnaPaeper** [AtlasOfLivingAustralia/spatial-hub#184]
CSDM user needs to be able to run an Area Report for a given location (lat, lon), or by a specified region (i.e. IBRA, LGA, State and Territory, Catchment, ?).

The Area Report should provide (TBC):
• a list of species with raw occurrence records in the area
• a list of species with modelled occurrence in the area
• and other Area Report info??

------------------

See [Workflow ](https://confluence.csiro.au/display/CSDM/Workflows#Workflows-ModeloutputsearchinSPwithon-the-flyimportoflayersfromObjectStore+Areareport)for details 

- Create CSDM data resource ID.
- Setup mechanism to poll BCCVL CKAN object store for new files (daily??? TBD).
- Retrieve polygon layers for different occurrence probabilities for CSDM models from object storage > 'Expert Distributions' 
- Assign expert distributions to new data resource.
- Store Expert Distributions in Spatial Layers storage with appropriate metadata (CSDM flag)
- CSDM Report Platform (SP Hub) with Area Report Tools only; restricted to CSDM Expert Distribution intersects - Interactive and PDF 'minimalist' versions ([mock-up](https://docs.google.com/document/d/1_x_fUDazOzruRlI1aaiV881aZQC6AI-AZzU48c54-Mw/edit?usp=sharing))
- Area Report - Enable intersect with all layers derived for a modelled species to create species/occurrence likelihood matrix

**Comment by CorinnaPaeper** [comment]
See [Workflow ](https://confluence.csiro.au/display/CSDM/Workflows#Workflows-ModeloutputsearchinSPwithon-the-flyimportoflayersfromObjectStore+Areareport)for details 

- Retrieve polygon layers for different occurrence probabilities for CSDM models from object storage (TBD) daily > 'Expert Distributions' 
- Store Expert Distributions in Spatial Layers storage with appropriate metadata (CSDM flag)
- Area Report - Interactive and PDF 'minimalist' versions (mock-up)
- Area Report - Enable intersect with all layers derived for a modelled species to create species/occurrence likelihood matrix

**Comment by m-hope** [comment]
Note: an additional task in this process is to check if the model was run using a dataset generated by the ALA's CSDM hub (ie: has an approprate DOI tag) and if so, add the model metadata to the dataset's DOI info (see issue #283).
