### ISSUE TITLE
Maxent fails

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-hub#186]
**Describe the bug**
Maxent prediction modelling fails

**To Reproduce**
Maxent model for Heleioporus australiacus with Humidity and Precipitation

**Screenshots**
<img width="1626" alt="Screen Shot 2019-04-17 at 12 40 52 am" src="https://user-images.githubusercontent.com/444897/56248752-99f1a200-60a9-11e9-819a-c1af09c11d24.png">

**Comment by adam-collins** [comment]
The Java warning no longer appears in the log. https://github.com/AtlasOfLivingAustralia/ala-install/commit/b473a18e9f363b86dfef1cb02148dadf7c7236be

It did not prevent maxent from running successfully.

**Comment by Tasilee** [comment]
Runs fine but produces a pop-up window that says An error occurred - as in #170

**Comment by Tasilee** [comment]
Now not running again. Locks up with progress bar "Running". Tested on Eucalyptus gunnii, Tasmanian extent, BIO best 5, 10% for testing. Re-ran by first mapping gunnii but same lock up.

**Comment by Tasilee** [comment]
Working again.
