### ISSUE TITLE
add to map / area not working

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/spatial-hub#187]
https://support.ehelp.edu.au/a/tickets/31577

But one of the specific problems I have is defining areas. This is the included screenshot (as JPG). The tool starts the task just fine, but cannot complete it as stays within the task, for as long as it is left. Other tasks, such as defining elevation or selecting species have led to error messages (without an error number unfortunately, so I can't be more specific).

(repeatable by MN)

![ALA SCREENSHOT AS](https://user-images.githubusercontent.com/9424545/56336320-42575180-61e3-11e9-8e47-361f385c191d.JPG)

**Comment by Tasilee** [comment]
Fixed and notified.
