### ISSUE TITLE
/portal/postAreaWkt always returns empty JSON

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#188]
Calls to `/portal/postAreaWkt` always seem to return HTTP 200 with an empty JSON object `{}`. There are no visible errors in the log files on `aws-spatial-prod`.

The spatial-portal then ignores the failure and calls to `/ws/object/undefined`, which fails with HTTP 404 and leaves the spatial portal interface stuck with no error showing.

```
[REDACTED] - - [23/Apr/2019:10:10:36 +1000] "POST /portal/postAreaWkt HTTP/1.1" 200 12 "https://spatial.ala.org.au/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0" "-" request_time=0.008 upstream_response_time=0.008 upstream_connect_time=0.000 upstream_header_time=0.008 upstream_cache_status=-
[REDACTED] - - [23/Apr/2019:10:10:37 +1000] "GET /ws/object/undefined HTTP/1.1" 404 20 "https://spatial.ala.org.au/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0" "-" request_time=0.001 upstream_response_time=0.001 upstream_connect_time=0.000 upstream_header_time=0.001 upstream_cache_status=-
```

![Screen Shot 2019-04-23 at 10 07 07 am](https://user-images.githubusercontent.com/82365/56542071-d729c880-65b0-11e9-8696-72cfc29b16d3.png)

![Screen Shot 2019-04-23 at 10 07 37 am](https://user-images.githubusercontent.com/82365/56542073-d7c25f00-65b0-11e9-9210-292257a8ded6.png)

![Screen Shot 2019-04-23 at 10 07 22 am](https://user-images.githubusercontent.com/82365/56542072-d729c880-65b0-11e9-9d69-b3deb0a43d33.png)

This relates to helpdesk ticket number 31651

**Comment by adam-collins** [comment]
resolved
