### ISSUE TITLE
BCCVL integration broken

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#189]
The integration between BCCVL and the Spatial Portal is broken. The report from the BCCVL is:

```
I noticed last week that the Export to BCCVL from the ALA Spatial Portal is not working. As soon as you click the link it gives an Internal Server Error. Earlier this morning it did bring me to the BCCVL login page, but not back to the Spatial Portal once I logged in.

Our developer had a look and thinks it has something to do with an incorrect client id.

Can you please check on your side what is going wrong?
```

References ticket number 31682 on helpdesk

**Comment by Tasilee** [comment]
I reproduced this issue. First run brought me to BCCVL but no data. Second and subsequent two runs generated the BCCVL server issue.

**Comment by Tasilee** [comment]
Still not working.

**Comment by chuijbers** [comment]
Hi guys, this is still not working. The authentication process seems to be fine now, but then you get back to the SP and it hangs there. Any updates on progress? Thanks!

**Comment by Tasilee** [comment]
Seems ok just now.
