### ISSUE TITLE
Support additional metadata when producing a DOI for a dataset

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/spatial-hub#193]
"Pop-up window to capture:
a) Annotation of all filtering steps (required)
b) Generic annotation of dataset (optional)"

Filtering steps (including annotations?) to be captured in a SP Workflow Repository which gives an ID to each Workflow sequence to enable easier re-application of selected workflows to other datasets

**Comment by chrisala** [comment]
* Support for a "Step 4" on the export which allows for workflow annotation.  Phase 1 will capture the data as JSON formatted text.  A separate task will be added to retrofit this once the workflow repository has been created.
* Pass this additional data to the biocache downloads plugin.
* The downloads plugin should be modified to pass the additional data to the DOI service when minting the DOI.

**Comment by adam-collins** [comment]
Example save of a workflow using the `layer.uid` for use with testing at this stage.

```
return WorkflowService.save(item.name, true, LoggerService.get(layer.uid), true).then(function (response) {
  bootbox.alert(JSON.stringify(response.data))
});
```

The response contains a URL for use inclusion with metadata.

This mechanism will change when annotations are made mandatory.
