### ISSUE TITLE
Script error downloading species list for area

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/spatial-hub#197]
**Describe the bug**
Clicking on "download species list for area" doesn't work (produces a javascript error).

**To Reproduce**
1. Import an area
2. Click on 'Quick links 3 - download species list for "your area"'

3.**Expected behavior**
A species list is downloaded.

**Actual behavior**
Nothing happens, there is a script error in the console.
Cannot read property 'name' of undefined
    at Object.getSpeciesLayerQuery (application.unminified.js:23864)

**Comment by Tasilee** [comment]
Still not working. Produces "504 Gateway Time-out" after ~5 minutes. Created a small rectangle area and then did Export | Species checklist.

**Comment by Tasilee** [comment]
Fixed
