### ISSUE TITLE
Add to Map | Area | Gazetteer polygon for Dynamic Landcover not working

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#198]
**Describe the bug**
"Add to Map | Area | Gazetteer polygon" is not working for the dynamic landcover layer

**To Reproduce**
1. Go to 'Add to Map | Area'
1. Click on 'Gazetteer polygon'
1. Enter "Open alpine"
1. No class is displayed but it exists

**Expected behavior**
The class "Open alpine...." should be selectable from the list of classes in the layer Dynamic landcover

**Actual behavior**
The target class is not exposed in the interface. If you do 'Add to Map | Layer | National dynamic landcover', you will see that the class exists.

![Capture](https://user-images.githubusercontent.com/6656350/57264924-3b23b500-70b8-11e9-84b8-53c64f750d24.jpg)

**Comment by qifeng-bai** [comment]
Linked to LogService

**Comment by Tasilee** [comment]
Tests OK.
