### ISSUE TITLE
Add to Map | Area | Define environmental envelope - not working

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#199]
**Describe the bug**
The area generation option that uses environmental an environmental envelope is not working.

**To Reproduce**
1. Go to 'Add to Map | Area | Define environmental envelope"
1. Enter "Bio01" into the search box
1. Select layer "Bio01"
1. Set maximum temperature to "8"
1. Press "Next"
1. SP locks up

**Expected behavior**
The area created defined by the temperatures should be generated as a new layer (of type area/polygon).

**Actual behavior**
Progress bar is displayed but no further outcomes. It locks up.

**Comment by qifeng-bai** [comment]
The same

**Comment by qifeng-bai** [comment]
Linked to LogService and biocache overload

https://biocache-ws.ala.org.au/ws/occurrence/facets?facets=names_and_lsid&flimit=0&q=qid:1557381736005 is not accessible

**Comment by Tasilee** [comment]
Working now, but results screen is totally blank. This is not needed anyway as the result is the new polygon layer.

**Comment by Tasilee** [comment]
Appears to be working and produces results screen and polygon area. However, Species count reporting against layer bounds spinning wheels. We are close :)

Tested with Bio01 min to 6.0

**Comment by Tasilee** [comment]
Now ok. Assume biocache issue.
