### ISSUE TITLE
Tools | Area report - PDF not working

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#200]
**Describe the bug**
The PDF area report is locking up on a small (25sqkm) area

**To Reproduce**
1. Zoom into a small area (say 5km by 5km)
1. Go to 'Tools | Area report - PDF'
1. Click on 'Current extent" radio button
1. SP locks up

**Expected behavior**
The Window with the progress should list  subcomponents as they are actioned

**Actual behavior**
The progress bar window comes up but there is no progress. The system locks and has to be cancelled.

**Comment by qifeng-bai** [comment]
Linked to LogService
