### ISSUE TITLE
Tools | Scatterplot - single not working

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#201]
**Describe the bug**
The progress bar window comes up and does not progress. The system hangs and the job has to be cancelled

**To Reproduce**
1. Zooom map to Tasmania
1. Go to 'Tools | Scatterplot - single'
1. Use 'Current extent' radio button
1. Enter species name "Eucalyptus gunnii"
1. No background species
1. Enter "Bio01" into layer select box and select it
1. Enter "Bio12" into layer select box and select it
1.  Press Next
1. Progress window doesn't progress

**Expected behavior**
A scatterplot should be produced

**Actual behavior**
Progress bar window is displayed but locks and Cancel button has to be pressed.

**Screenshots**
![Capture_2](https://user-images.githubusercontent.com/6656350/57265464-36143500-70bb-11e9-95a2-06760dde398f.jpg)

**Comment by qifeng-bai** [comment]
May relate to 
No mapping found for HTTP request with URI [/ws/checklist/lsid/http:/id.biodiversity.org.au/node/apni/2903267

**Comment by qifeng-bai** [comment]
#207 Working now

**Comment by qifeng-bai** [comment]
![Screen Shot 2019-05-14 at 2 47 23 pm](https://user-images.githubusercontent.com/31238531/57671501-6594e580-7657-11e9-99d4-cb48415d4921.png)

**Comment by Tasilee** [comment]
Agree: working as it should.
