### ISSUE TITLE
Tools - Compare areas works inconsistently

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#203]
**Describe the bug**
The 'Compare areas' tool process locks up after submission

**To Reproduce**
1. Zoom to a small area
1. Use 'Add to Map | Area | Draw bounding box' to create a small area
1. Pan to an adjacent area
1. Use 'Add to Map | Area | Draw bounding box' to create a second small area
1. Click on 'Tools | Compare areas'
1. Select 'My rectangle-1'  and 'May rectangle' areas
1. Select "All species"
1, Press the 'Next' button
1. Progress bar window is displayed but no progress is made. It locks up.

**Expected behavior**
The process should result in a report of what species are in each area

**Actual behavior**
The progress bar window locks up and the 'Cancel' button has to be clicked.

**Comment by qifeng-bai** [comment]
Linked to LogService bugs

**Comment by Tasilee** [comment]
This remains totally inconsistent. Three tests just now - two worked, one failed and I cannot at this point see why the difference. Same happened yesterday. Inconsistent is worse than outright fail all the time.

failed (id:133003)
compare species
sort species lists
My Rectangle: list species
My Rectangle: count occurrences
My Rectangle: define area
My Rectangle-1: list species
My Rectangle-1: count occurrences
My Rectangle-1: define area

**Comment by Tasilee** [comment]
Seems good.
