### ISSUE TITLE
Tools | predict doesn't work

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#206]
**Describe the bug**
Once the parameters are entered, the progress bar window locks up.

**To Reproduce**
1. Zoom to Tasmanian extent on the map
1. Go to 'Tools | Predict'
1. Click on 'Current extent' radio button
1. Under 'Search for species, enter 'Eucalyptus gunnii'
1. Under 'Search layers', select 'BIOCLIM 1960 best 5' option
1. Click 'Next' button
1. Progress bar window locks up

**Expected behavior**
A prediction layer should be produced and a report downloaded.

**Actual behavior**
Once the 'Next' button is pressed, the progress bar window comes up and locks up. You have to press the 'Cancel' button to stop.

**Comment by qifeng-bai** [comment]
Same as other issues

**Comment by Tasilee** [comment]
Working nicely!
