### ISSUE TITLE
Bugs related logService

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-hub#207]
8. Add to Map | Area | Gazetteer polygon | open alpine (not working)
-- > Add logProxy
9. Add to Map | Area | Environmental envelope | Bio01 (3.4-8) | Bio12 (3000-5760) (not working)
--> Biocache overloaded
 11. Add to Map | Facet | User annotations (not working)

 13. Tools | Area report - PDF | Envelope (not working)
   -> wrong variable name
 14. Tools | Scatterplot - single | E.gunnii, E.nitida | Current extent (Tasmania) | Grid | Bio01, Bio12 - Facet on land cover (not working)
> 15. Tools | Taxon frequency | Current extent | E.gunnii / Eucalyptus | 1900-  (not working)
> 17. Tools | Compare areas | rectangle 1 vs rectangle 2 | Eucalyptus (not working)
 -> wrong variable name
> 18. Tools | AOO | Eucalyptus gunnii | Current extent (Tasmania) (not working)
> 19. Tools | Classify | Tasmania | 10 | Best 5 bioclim (not working)
> 20. Tools | Predict | E.gunnii | Current extent (Tasmania) | Best 5 | 10% (not working)

**Comment by qifeng-bai** [comment]
Mainly because the LogService causes the CORS issue.  Building a proxy for solving them

**Comment by qifeng-bai** [comment]
URL mapping of reporting issue for /tasks/output/ 

Adam new changed to "/tasks/output/$p1/$p2?/$p3?(.$format)?"(controller: "tasks", action: "output")
I added an original url :  "/tasks/output/$p1/$p2?"(controller: "tasks", action: "output")

**Comment by Tasilee** [comment]
#199 not working again

**Comment by qifeng-bai** [comment]
#206 works

![Screen Shot 2019-05-14 at 2 47 23 pm](https://user-images.githubusercontent.com/31238531/57671531-865d3b00-7657-11e9-94b1-906afc6e1660.png)
