### ISSUE TITLE
Species layer metadata link not working

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#208]
**Describe the bug**
Map any species as a point layer and clicking on (i) for the metadata and link to records is not working at all.

**To Reproduce**
1. Go to 'Add to Map | species | Eucalyptus gunnii' | World
1. Click on '(i)
1. Nothing happens!

**Expected behavior**
Clicking on the metadata link should get you to a summary of the layer and the records in biocache.

**Comment by qifeng-bai** [comment]
Yes, again, CORS issue.

**Comment by qifeng-bai** [comment]
It is working after I refresh the page

**Comment by Tasilee** [comment]
It is not working for me. I cleared cache and started new session.

**Comment by Tasilee** [comment]
Tested and OK
