### ISSUE TITLE
Tools | Taxon frequency graph order and labelling changes needed

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#210]
**Describe the bug**
The ordering of the graphs needs to be more logical and the Y-axes label of the ratio graphs needs to use "Ratio", not "Count", otherwise it is confusing.

Order

1. Frequency histogram
1. Cumulative frequency graph
1. Frequency ratio graph (change Y-axis label to "Ratio")
1. Cumulative frequency ratio graph (change Y-axis label to "Ratio")

**Comment by qifeng-bai** [comment]
https://spatial.ala.org.au/ws/tasks/output/133515/charts.html

There is still one change needed to be done

**Comment by Tasilee** [comment]
Nice.
