### ISSUE TITLE
Tools | Compare areas - CSV has duplicate taxa entries

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#211]
**Describe the bug**
Compare two areas results in a CSV that details what species are in which of the two areas. However, each taxon has multiple line entries in the table.

**To Reproduce**
1. Go to 'Tools | Compare areas'
1. Click on 'Define new area' button
1. Select "Enter area coordinates (WKT)'
1. Enter for Area-1 "MULTIPOLYGON(((142.374572753906 -35.016500995886,142.522888183594 -35.016500995886,142.522888183594 -34.912962495217,142.374572753906 -34.912962495217,142.374572753906 -35.016500995886)))"
1. Repeat for Area-2 with "MULTIPOLYGON(((142.289428710938 -37.0266767305112,142.432250976562 -37.0266767305112,142.432250976562 -36.9279389977668,142.289428710938 -36.9279389977668,142.289428710938 -37.0266767305112)))"
1. Select Area-1 and Area-2
1. Select "All species"
1. Press Next

**Expected behavior**
There should be one record in the CSV for each taxon.

![Capture](https://user-images.githubusercontent.com/6656350/57826385-6f991e80-77e6-11e9-86be-7fa871a27af9.jpg)

**Comment by Tasilee** [comment]
Looks good!

**Comment by Tasilee** [comment]
Nope, did a more thorough check and it is still writing multiple lines for the same species (same LSID).

**Comment by Tasilee** [comment]
Now get "failed (id:144401)" on two small rectangular areas about 13sqkm each.

**Comment by Tasilee** [comment]
Now running but same taxa problem - taxa are replicated multiple times in the output CSV. See attached example
[comparison.xlsx](https://github.com/AtlasOfLivingAustralia/spatial-hub/files/3295051/comparison.xlsx)

**Comment by Tasilee** [comment]
I created two simple areas, ran **Tools | Compare areas**, then did two separate **Tools | Area reports** and compiled the result into the attached single file (see worksheets).
[Compar areas.xlsx](https://github.com/AtlasOfLivingAustralia/spatial-hub/files/3518161/Compar.areas.xlsx)

**Comment by adam-collins** [comment]
Part of 0.3.2
