### ISSUE TITLE
Biocache performance mitigations

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#217]
As an outcome of the biocache performance and stability meeting in May 2019, a number of biocache/SOLR performance issues were identified. These included a number of "expensive" SOLR queries that had the potential to cause one or more SOLR nodes to freeze. SP was a common "trigger" for many if these so this issue is to try and put in place limits on these queries.

- [ ] queries with long lists of taxa (either provided or via specieslist-webapp). @djtfmartin suggests a limit of 200 taxa (debatable/negotiable). So SP should respsect the limit and only include the first 200 (limit) taxa

- [x] Rate limit queries to biocache-service from client. E.g. Detailed area report which can trigger >20 separate requests. This would need more testing to find out what the thresholds are and then to possibly wait for batches of requests (10 say) to complete before firing off the next batch?

- [x] implement a delay mechanism on the map component of the biocache/spatial portal/hubs to prevent sending immediate requests to the server. Many users try to navigate on the map by zooming and panning rapidly to focus on a region and every move sends many mapping requests which causes nginx rate limit exceeding for tiles that won't be looked at. [high priority]

- [ ] Add limits to area reports to prevent large "World" and "Australia" for all species to be requested.

**Comment by qifeng-bai** [comment]
Also linked to task https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/340
