### ISSUE TITLE
 A couple of Spatial Portal issues that EarthWatch have noted also

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/spatial-hub#220]
This is a copy of ticket https://support.ehelp.edu.au/a/tickets/34529 raised by Taryn.

Hi Support Team,
 
There are a few SP issues. I brought some of these up in ticket #32226 but they were not resolved then. I have been contacted about this problem by the people at [ClimateWatch](https://support.ehelp.edu.au/a/tickets/34518) as it is a process outlined in their educational resources.
 
The instructions in the resources are here:

![image](https://user-images.githubusercontent.com/8326394/58841994-a3fa4f00-86af-11e9-8f3b-015f7fd12b2c.png)

https://spatial.ala.org.au/?q=*:*&fq=geospatial_kosher:true&lat=-35.2488&lon=149.1535&radius=1.0
 
Here is a link that might help you understand the first problem.
 
I can’t screen shot the second problem, but if you try to follow the above instructions, you will see what I mean here.
 
Feel free to ask me if you don’t understand what I mean here, it’s heaps easier for me to explain it in person.
 
Regards, Taryn

**Comment by javier-molina** [comment]
@adam-collins, @Tasilee fya

@M-Nicholls fyi

**Comment by Tasilee** [comment]
Confirmed  first part:
![Capture](https://user-images.githubusercontent.com/6656350/58847821-a668a300-86c7-11e9-88aa-c6fd58c50b5d.jpg)

**Comment by Tasilee** [comment]
Second issue is not correct: 'Data provider is there'

![Capture_2](https://user-images.githubusercontent.com/6656350/58847945-02cbc280-86c8-11e9-8ded-2bda5b4071f2.jpg)

**Comment by Tasilee** [comment]
Tested - OK
