### ISSUE TITLE
Add ability for users to generate a DOI for occurrence maps

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/spatial-hub#222]
As a Spatial Portal user I want to use the maps I create for my publications.

The Service Portal must allow a user to create a DOI for occurrence maps similar as Biocache downloads.

The DOI will include the dataset used to generate the map.

This will enable users to cite the map in their publications.

See conversation on https://support.ehelp.edu.au/a/tickets/34567 for an example of the business case around this requirement.

**Comment by Tasilee** [comment]
Fair point. I would agree that a map is a 'product' of the ALA and should (like our PDF area reports) have a DOI. The only hassle at the moment is the limitations of the prior 'Export | Map' option. I found it far worse than simply doing a screen capture (of a selected area - the map). We were also getting a lot of 'I can't do xxx' with the export. E.g., #162 and https://github.com/AtlasOfLivingAustralia/spatial-service/issues/38. 

We **do** need a better 'Export | Map' and @adam-collins said that this would require our hosting of at least the Opentreetmaps basemaps if we were to get decent resolution - required for publications.  

The key issue is what priority we put to this based on what resources are required (@adam-collins?) and on user impact.
