### ISSUE TITLE
Filtering tool - Charts

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#224]
Need a chart component for interacting with a facet to change a facet selection.

**Comment by temi** [comment]
https://upsource.ala.org.au/spatial-hub/review/SH-CR-8

**Comment by Tasilee** [comment]
Tested OK on nex spatial test. Minor issue with chart selection slider  on larger window (only)- when dragging down will only select first two classes. Selecting/deselecting via chart bars works a treat though.

**Comment by Tasilee** [comment]
Part 2: (i) charts. Great but who selects which charts? This is a similar issue to facet classification.  I would suggest for generic summaries, the best 8 facets would be

1. Name match metric
1. Decade or year
1. Month
1. Assertions
1. Dynamic land cover class
1. Record type (dwc:basisOfRecord PLEASE!)
1. dwc:license
and ideally

1. Precipitation - driest quarter (Bio17)
1. Temperature - coldest quarter (Bio11)
