### ISSUE TITLE
Truncated list from Add to Map | Gaz polygon

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#228]
**Describe the bug**
The list of gazetteer entries is truncated when the entries are greater than about 20 entries. If you are searching for "Victoria", you will never see it in the list.

**To Reproduce**
1. Go to 'Add to Map | Area | Gazetteer polygon"
1. Enter "Victoria"
1. "Victoria" as a State is not listed as it is off the bottom the the 20 entries displayed.

**Expected behavior**
We require a mechanism for scrolling/paging larger lists or filtering by a classification

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6656350/59314832-71c59e80-8cfa-11e9-8b5c-b8b66508e84d.jpg)

**Comment by qifeng-bai** [comment]
Categorise  layers and turn dropdown list scrollable if oversize

**Comment by Tasilee** [comment]
Just tested on nectar-spatial-test the Add to Map | Area | Gazetteer polygon: 1) We should just "Show X filters" by default rather than expect users to click on it? 2) "Show more" and slider work well.

**Comment by Tasilee** [comment]
Tests good on Production.
