### ISSUE TITLE
Create area from selecting contextual classes in legend odd

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#229]
**Describe the bug**
The filtering to the subset of classes works fine but when a number of classes are selected, and 'Create area' is used, it colours up the new areas in multiple colours and appears to create/display areas even though they are unselected.

**To Reproduce**
1. Go to 'Add to map | Layer'
1. Select 'CAPAD 2014 terrestrial classes'
1. Filter using "wilderness"
1. Press "Create area" button
1. See issues

**Expected behavior**
Selected areas should be either all same colour (default I presume) or original colours? When CAPAD and new (4) area unselected, no areas should be visible.

**Actual behavior**
At least two colours of new area are created and some areas remain displayed regardless of all layers being de-selected.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6656350/59575728-061b7100-9100-11e9-916b-8ad2727efd6d.jpg)

**Comment by Tasilee** [comment]
Describe the bug
When a number of classes are selected from a contextual layer legend and Create area is clicked, there is a new layer created but it is not the merge of the selected areas.

To Reproduce
Steps to reproduce the behavior:

Go to 'Add to Map | Layer'
Select "CAPAD 2016 terrestrial classes" and map it
Select a number of classes in the legend
Click the Create area button below the legend
A new layer is created but it is not the polygons of the selected classes
Expected behavior
The new layer should be the spatial union of all the polygons of the selected contextual layer classes

Actual behavior
A new layer is created but it does not represent the polygons of the selected area

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/267ceb21152999072564f87bcee691c8ee79e7b9
