### ISSUE TITLE
Several angular errors and missing toolbar after update spatial-hub

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/spatial-hub#231]
After updating: 
https://espacial.gbif.es/
via `ala-install` the client toolbar is missing:

![](https://i.imgur.com/VHvVD4k.png)

and we get some angular errors:

![](https://i.imgur.com/m9GQ57j.png)

I'm using an inventory similar to the Paris Workshop inventory:
https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/inventories/workshop/spatial-livingatlas.yml
and an updated `ala-install` repository.

I tried:
```
spatial_hub_version = 0.3.0-SNAPSHOT
spatial_hub_version = 0.3.1-SNAPSHOT
```
with similar results.

I also deployed a new spatial demo VM with same results.

Maybe is related with https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/5e2d22bb6831fe1605197d1dba957529d92029c5 ? cc @adam-collins

**Comment by adam-collins** [comment]
In this instance https://espacial.gbif.es/portal/config/menu redirects to https://espacial.gbif.es so there is no data to build the toolbar. Is there a redirect on `https://espacial.gbif.es/portal` ?

The /portal/config/menu should return data to build the toolbar, e.g. https://spatial.ala.org.au/portal/config/menu

**Comment by vjrj** [comment]
Sorry, I was getting a `401`, and I though that was a `nginx` configuration issue:
https://github.com/AtlasOfLivingAustralia/ala-install/issues/297
so I configured something similar to `/webportal` location configuration.

Removing again my manual `/proxy` configuration, I get the 401 again:
https://espacial.gbif.es/portal/config/menu
is any other new `nginx` location conf that we are missing?

Thanks @adam-collins

**Comment by vjrj** [comment]
One more related thing, the [README](https://github.com/AtlasOfLivingAustralia/spatial-hub/blob/master/README.md#menu-configjson) mention `/data/spatial-hub/menu-config.json` but I think should be `/data/spatial-hub/config/menu-config.json`. Same with `view-config.json`. In both locations I get a `401`.

**Comment by vjrj** [comment]
I cannot reproduce this anymore.
