### ISSUE TITLE
Restrict access by user role

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#232]
**Is your feature request related to a problem? Please describe.**
Need the ability to restrict access to a spatial-hub `hub` by user role.

**Describe the solution you'd like**
* A configuration option `user_roles` that may differ for each spatial-hub `hub`. 
* `user_roles` is an array of values.
* Valid values for `user_roles` are:
  - empty for login is not required
  - `*` for any user that is logged in 
  - user role name 
* All access is permitted when CAS is disabled.
* A redirect to CAS login page occurs when the user is not logged in and a login or a specific user role is required.
* An `access denied` page is displayed when a user is logged in and does not have access.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Tasilee** [comment]
- user account login required for https://nectar-spatial-test.ala.org.au (CHECKED: OK)
- user account with csdm role login required for https://nectar-spatial-test.ala.org.au/hub/csdm (CHECKED: OK)
- no login is required for https://nectar-spatial-test.ala.org.au/hub/embed (CHECKED: OK)

**Comment by adam-collins** [comment]
Part of 0.3.2
