### ISSUE TITLE
Area merge would greatly benefit from union (as now) or intersection (requested)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#234]
**Is your feature request related to a problem? Please describe.**
Ticket https://support.ehelp.edu.au/a/tickets/35604 raised the need to enable species distributions (from say expert distribution, AOO, EOO, alpha hull or Maxent) to be 'cookie-cut' by say the Australian coastline. For example, a terrestrial species should show a polygon that was only terrestrial. Vice-versa for marine.

**Describe the solution you'd like**
We have an existing MERGE option in Add to Map | Area. This is in effect, a union of one or more area (polygon) layers.  We could add an intersection option that was limited to two polygon layers where the first layer cookie-cut the second layer. The output layer would have area (sqkm) associated with its metadata. This provides a general solution that could be used for multiple applications. For example the cells in the Tabulation tool are in effect, intersections between contextual layer classes.

**Describe alternatives you've considered**
While we could add a post-processing layer intersect to say Tools | AOO, EOO, we would need for generality to add it to others such as MaxEnt. This seems a more insular and restrictive solution.

Example application:

![image](https://user-images.githubusercontent.com/6656350/60476450-fcc50380-9cbe-11e9-89e4-b5106b40fa89.jpeg)

**Comment by Tasilee** [comment]
An intersection/union function has now been tested on the spatial-test site and works well.

**Comment by adam-collins** [comment]
Part of 0.3.2
