### ISSUE TITLE
If a layer is deselected or deleted, highlight top layer in list

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/spatial-hub#235]
If I have multiple layers on my map, when I deselect one of those layers the legend units are visible for the deselected layer rather than the visible layers on the map. This is confusing when the colour scales are similar, e.g. if the layers are annual mean precipitation and annual mean temperature. You end up with a temperature appearing to be measured in mm or precipitation measured in degree celsius. 
![image](https://user-images.githubusercontent.com/23368496/60775860-81ee6380-a16a-11e9-907f-fc03a9a23816.png)

It would make more sense to me if once a layer was deselected, it was no longer highlighted. Instead the active layer highest in the list of layers was highlighted and the legend reflected whatever units are relevant to that layer.

An alternative solution would be leave the deselected layer highlighted, but show the units for the highest active layer - however this is likely to also be confusing.

**Comment by RobinaSanderson** [comment]
Hi @tasilee - Issue raised as requested.

**Comment by Tasilee** [comment]
Thanks @RobinaSanderson. Appreciated. I agree this is confusing and has lead to a lot of small hassles during workshops. 

Discussed this with @adam-collins and figure a solution is to AUTOMATICALLY display the legend for the topmost selected layer.  This will I think work.
