### ISSUE TITLE
Legend is showing values from a different field on the same layer

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#237]
**Describe the bug**
The Legend for `CAPAD 2016 Marine` in `nectar-spatial-staging` is incorrectly showing values from `CAPAD 2016 Marine (Classes)`

**To Reproduce**
1. Go to `https://nectar-spatial-staging.ala.org.au/`
2. Click on 'Add to Map' and then `Layer`
3. Search for and select `CAPAD 2016 Marine` and click `Next >`
4. Click on `CAPAD 2016 Marine`
5. Notice that the legend contains unexpected classes, which appear to be from the other field on the same layer, `CAPAD 2016 Marine (Classes)`

**Expected behavior**
Legend shouldn't show values from a different field.

**Actual behavior**
Legend shows values from a different field on the same layer.

**Screenshots**
![Screen Shot 2019-07-16 at 3 24 07 pm](https://user-images.githubusercontent.com/82365/61268274-47c23900-a7de-11e9-9c9b-64bc808a4364.png)

**Additional context**
N/A

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/tree/issue-sp-237-fix-adding-multiple-layer-styles

**Comment by Tasilee** [comment]
Tested ok.
