### ISSUE TITLE
NPE Cannot invoke method get() in gsp_spatial_hub_portalindex_gsp.groovy:53

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/spatial-hub#238]
**Describe the bug**
After updating https://espacial.gbif.es (using `0.3` or `0.3.1-SNAPSHOT`) I get:

a error message in screen:  "An error has occurred" and this in `tomcat` logs:

```
18:56:32.649 [http-bio-127.0.0.1-8080-exec-6] ERROR o.s.boot.web.support.ErrorPageFilter - Forwarding to error page from request [/] due to exception [Error processing GroovyPageView: Cannot invoke method get() on null object]
org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: Cannot invoke method get() on null object
        at org.grails.web.servlet.view.GroovyPageView.createGroovyPageException(GroovyPageView.java:135)

(...)

Caused by: java.lang.NullPointerException: Cannot invoke method get() on null object
        at gsp_spatial_hub_portalindex_gsp$_run_closure2.doCall(gsp_spatial_hub_portalindex_gsp.groovy:53)
        at org.grails.taglib.TagBodyClosure.executeClosure(TagBodyClosure.java:200)
```

**To Reproduce**

We use an spatial inventory quite similar to Paris workshop but with CAS and https enabled. I tested also without CAS and without https and the error is still present. Also with a new VM (not updating).

**Comment by vjrj** [comment]
If I access to https://spatial.ala.org.au I'm redirected to the CAS login. 

This is quite new, but this redirect doesn't happens to other deployed portals like https://espacial.gbif.es so any user info like userId is empty, etc. and give this NPE errors.

I think this is the same issue than this 401:
https://github.com/AtlasOfLivingAustralia/ala-install/issues/297

It looks like some different CAS configuration is running in spatial-hub ALA production configuration than the generated by `ala-install`:

```
security:
  cas:
    casServerName: "https://auth.gbif.es"
    uriFilterPattern: "/portal.*,,/,/alaAdmin,/alaAdmin.*"
    uriExclusionFilterPattern: "/portal/messages.*,/portal/sessionCache.*,/static.*,/assets.*"
    authenticateOnlyIfLoggedInFilterPattern: ""
    appServerName: "https://espacial.gbif.es"
    casServerUrlPrefix: "https://auth.gbif.es/cas"
    loginUrl: "https://auth.gbif.es/cas/login"
    logoutUrl: "https://auth.gbif.es/cas/logout"
    contextPath: "/"
    bypass: false
    disableCAS: false
    gateway: False
```

We have some spatial portals (Spain, Austria, now Tanzania) having this issue.

Thanks @djtfmartin for the help debugging this. cc @geonb

**Comment by vjrj** [comment]
I found that this issue was introduced here: https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/e2668b001c168134b23f93f4942e3cd32d63c3c4 the previous builds works for me

**Comment by vjrj** [comment]
I just tested with last changes in [ala-install role](https://github.com/AtlasOfLivingAustralia/ala-install/commit/df189487eb3ab80275ceeca437d87f2349564b91) and  https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/4db07ccb256420e8abec0d2f6ed7cf4e1f596975 with same results. If I can help testing, etc, just ask.

**Comment by vjrj** [comment]
I updated our spatial service using the last changes in `ala-install` and I get the same error with `0.3.1`.

cc @jloomisVCE

**Comment by vjrj** [comment]
I've debugged this and I've found that this occurs when `google.apikey` is not configured (the default when using `ala-install`).

I'll send also a PR to `ala-install` to allow the configuration of this variable (and also the language).

cc @geonb @jloomisVCE and @djtfmartin

**Comment by adam-collins** [comment]
Part of 0.3.2
