### ISSUE TITLE
Creating and using an "on the fly"  species list

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/spatial-hub#239]
**Describe the bug**
I have tried to create a list of species to add to the map via the spatial portal interface. I can't see the list I create in the spatial portal, but I could see it in the lists tool.

**To Reproduce**
Steps to reproduce the behaviour:
1.	Choose Add to map | species
2.	Type name into search box and select taxa for list (I selected 4 acacia species)
3.	Click next
4.	Enter name and description, left Private checkbox selected
5.	Click next

**Expected behavior**
1. List is created in lists.ala.org.au
2. Layer is created in spatial portal with name of list
3. Layer includes occurrences or all listed species
4. Layer is displayed in spatial portal interface and is automatically the selected layer

**Actual behavior**
1. Spatial portal appears to hang when you click Next
2. If you look at lists.ala.org.au the list has been created

**Screenshots**
Step where it hangs
![image](https://user-images.githubusercontent.com/23368496/61600683-3a40ff00-ac75-11e9-854a-a1610b33d886.png)

List in lists tool
![image](https://user-images.githubusercontent.com/23368496/61600832-1cc06500-ac76-11e9-80c4-3d896da9bdfb.png)

**Additional context**
1. If you click the Next button multiple times in the spatial portal, you get multiple lists created.
2. If you are using lists you've created in the lists pool previous (not on the fly), you can't see Private lists in the spatial portal interface to select.

Private list in lists.ala.org.au
![image](https://user-images.githubusercontent.com/23368496/61600968-bbe55c80-ac76-11e9-8728-9331770a217e.png)

Not showing in Spatial portal interface
![image](https://user-images.githubusercontent.com/23368496/61600999-d4ee0d80-ac76-11e9-8307-6f0e58a4bf81.png)

**Comment by Tasilee** [comment]
tested ok
