### ISSUE TITLE
Not displaying legend on Add to Species|Density grid view

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/spatial-hub#240]
**Describe the bug**
Legend is not displaying when species list added to map and density grid view is selected.

The knowledge base article for **Add Multiple Species (Lists)** says:
“ The legend shows the species assemblage occurrence counts, e.g. 0 to 99, 100 to 199.”

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a species list already prepared in lists.ala.org.au
2. In Spatial Portal select **Add to map | species**
3. Select **Use species list**
4. Select a list to use
5. Spatial portal will display occurrence points
6. Select 'Display as Density Grid' radio button
7. Density grid view will display, but a legend is not included

**Expected behaviour**
Legend will display in layer options pane

**Actual behaviour**
No legend in the pane or elsewhere on the portal screen

**Screenshots**
![image](https://user-images.githubusercontent.com/23368496/61603842-952d2300-ac82-11e9-897e-ebd5127b4798.png)

**Additional context**
NA

**Comment by Tasilee** [comment]
tested OK
