### ISSUE TITLE
Inconsistent facets list used

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#242]
**Describe the bug**
The list of facets in `Add to map | Facets` differs from the species legend colour option facets.

**To Reproduce**
Compare the list of facets in `Add to map | Facets` and the species legend colour option facets that is available after mapping a species layer.

**Expected behavior**
`Add to map | Facets` facet list is incorrect. The correct list of facets is found in the specie legend.

**Actual behavior**
`Add to map | Facets` facet list is incorrect.

**Comment by Tasilee** [comment]
Tests OK.
