### ISSUE TITLE
Support selection/highlight of all contextual classes

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#243]
**Is your feature request related to a problem? Please describe.**
A number of well-informed users have assumed that they should be able to select a contextual class (or more than one) as you can do for occurrence facet classes. This makes sense - it is intuitive and would, add useful functionality, e.g., when colour classes are difficult to differentiate, or where you cannot locate the extent of a class. 

This should lead to the same function as in 'Create new layer with/without selection' which would also add significant functionality, e.g., create an area from a Classification class that could be used for an area report! Having convergent functionality across facets and contextual classes makes a lot of sense.

**Describe the solution you'd like**
Check boxes to the left of contextual layer classes. Clicking on a class, displays ONLY the area of that class in RED as we do now for point section using facets.

The ability to  'Create new layer with/without selection' would seem an ideal parallel with many applications.

**Describe alternatives you've considered**

**Additional context**
This issue has arisen a few times and is an obvious intuitive gap that we should address, if possible. It would improve consistency across the SP, always a good thing.

**Comment by Tasilee** [comment]
This appears largely done! Tried with CAPAD 2016 marine and selection works and create area button works well. As noted above however, do we ONLY display selected class in red - to match the new filtering function?

Minor error noted: de-selection of a class leaves selected class highlighted. If you select another class, the de-selected highlighted class is dimmed.

**Comment by adam-collins** [comment]
Fixed in 0.3.2
