### ISSUE TITLE
Load session doesn't restore session

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/spatial-hub#245]
loading a saved session doesn't restore the session correctly - e.g. layer isn't displayed:

https://spatial.ala.org.au?ss=1565056725248 (from support ticket https://support.ehelp.edu.au/a/tickets/37353)
replicated here-
https://spatial.ala.org.au/?ss=1565311687236

**Comment by Tasilee** [comment]
That link doesn't load CAPAD 2016 Terrestrial, but when I mapped the layer, Saved session and Loaded it, it restored fine:

https://spatial.ala.org.au/?ss=1565647108328

Ditto: https://spatial.ala.org.au/?ss=1565311687236

**Comment by Tasilee** [comment]
Discussed with @adam-collins and the problem is intermittent.

**Comment by Tasilee** [comment]
https://nectar-spatial-test.ala.org.au/?ss=1569985304940 didn't work as expected. Missing 3/5 layers
