### ISSUE TITLE
Download species list link fails with javascript error in getSpeciesLayerQuery

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#251]
**Describe the bug**
`Download species list` silently fails.

**To Reproduce**
1. Go to `https://spatial.ala.org.au/`
2. Open Developer Tools in browser
3. Click on `Add to map` and then `Area`
4. Click on `Gazetteer polygon` and then `Next>`
5. Type `Victorian Midlands` and then select the `IBRA 7 Regions` option and then `Next>`
6. Under `Quick links`, click on `Download species list for "Victorian Midlands"`
7. See the following error referencing `getSpeciesLayerQuery` in the Javascript Console in Developer Tools:
```
Error: a is undefined
getSpeciesLayerQuery@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:2756:28
.controller</b.open@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:2527:20
.controller</b.delegateCall@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:2528:31
fn@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js line 1650 > Function:4:264
c@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:1543:231
e@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:1693:394
$eval@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:1562:482
$apply@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:1563:202
compile/</<@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:1693:446
dispatch@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:103:306
add/g.handle@https://spatial.ala.org.au/assets/application-486b5357eb0cac62a551a8d67b9d0ffa.js:97:65
```
**Expected behavior**
Some form of species list should be downloaded.

**Actual behavior**
It is horribly silently broken.

**Screenshots**
![Screen Shot 2019-09-02 at 8 57 22 am](https://user-images.githubusercontent.com/82365/64083288-c2c8ba00-cd60-11e9-8d75-b5847ded7644.png)

**Additional context**
Firefox 68.0.1 on macOS 10.14.5

References ticket 39604 in helpdesk

**Comment by adam-collins** [comment]
Same as #253

**Comment by timhicks-ala** [comment]
@adam-collins @nickdos - another instance of it in ticket 45310. I see the same behaviour with a simple point-radius area. I've discovered the species list download works as long as at least one species has also been added to the portal (doesn't matter if there are any records of that species in the area, one just has to be added) so there is that workaround.

**Comment by timhicks-ala** [comment]
It is possible to download the species list without adding a species layer by going to the Area report instead, and clicking List and then Download from there. So the issue is entirely with the Download species list option on the main view.

**Comment by Tasilee** [comment]
Thanks @timhicks-ala. The **Tools | Area report - interactive** is certainly a work-around, but as it does a lot more and takes a lot longer, and there is a demand for the simpler **Export | Area checklist**, then I'd like to see this issue solved. 

And BTW, can we please rename this to "Species checklist" as that is the proper term.

**Comment by adam-collins** [comment]
Part of release 0.3.2
