### ISSUE TITLE
Predict tool - missing point layer, 2 prediction layers, legend not showing

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/spatial-hub#256]
**Background**
When I run the predict tool I get the following issues:
- No point layer
- 2 prediction layers
- no legend either by "Show legend" or "Pop up legend"

**Steps to recreate**
- login to spatial portal
- select Tools | Predict
- select Tasmania as the area
- enter "Eucalyptus Gunnii" as the species
- Search for and select "bio01" and "bio12" as the layer (annual temperature and annual precipitation)
- Run predict tool
- select Show legend
- select popup legend

**Expected results**
- one prediction layer
- one points layer
- legend visible in "Edit layer options" section if "Show legend" is selected
- pop up legend visible if "Pop up legend" is selected

**Actual results**
- No point layer
- 2 prediction layers
- no legend either by "Show legend" or "Pop up legend"

**Screenshots**
![image](https://user-images.githubusercontent.com/23368496/64496959-9a573780-d2ed-11e9-9451-55d40416c07e.png)

**Comment by Tasilee** [comment]
failed (id:1636)

**Comment by Tasilee** [comment]
Re-tested on E.gunnii Tasmanian extent BIOCLIM best 5 and it only picked up one of the five layers (Bio17) - ah, only a subset available in test...a bit dangerous. Otherwise, all good.

**Comment by adam-collins** [comment]
`spatial-service` was running twice. This is now fixed.
