### ISSUE TITLE
Add option for layer display to hide colours

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#257]
A recent change has resulted in the states & territories layer to show different colours for the various values (states). Previously states & territories were all the same colour, which differed from most of the other layers which had colours assigned to the different layer values.

The user has requested an option to hide the colours, as it interferes with the visibility of records layers. Thus they prefer the way it used to behave. 

See ticket https://support.ehelp.edu.au/a/tickets/38337

**Comment by nickdos** [comment]
@adam-collins commit links.

**Comment by adam-collins** [comment]
Partial progress https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/0aa9938ae33160a8810008d381ec5c7c74176295 https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/08a92d32dc10e5f93dbb7b4d831a4b7f10259bc8

**Comment by adam-collins** [comment]
Partial progress https://github.com/AtlasOfLivingAustralia/spatial-service/commit/1e8ed0aa0b98790cdce7ccda0215f694c1999bf2 and AdminController.defaultGeoserverStyles() in https://github.com/AtlasOfLivingAustralia/spatial-service/commit/08bdeb754ae26135587fb1a86466b93c96cf28da

**Comment by adam-collins** [comment]
Partial progress https://github.com/AtlasOfLivingAustralia/layers-store/commit/a79749d8d2a3ee9c03231c2c782ff9676161b716

**Comment by qifeng-bai** [comment]
PR: https://github.com/AtlasOfLivingAustralia/spatial-service/pull/161

**Comment by qifeng-bai** [comment]
@adam-collins  I am wondering if the style of 'outline polygon' can be added via Ansible script, when we setup a server?

**Comment by Tasilee** [comment]
Tested and the options for default, outline and filled mode works first up and works on re-selections. If however, any of the areas (classes) are selected then deselected, those options no longer work.
![Capture_2](https://user-images.githubusercontent.com/6656350/107891585-b562b800-6f73-11eb-89b0-25889ee4fd3b.jpg)

**Comment by qifeng-bai** [comment]
@Tasilee I have done some tests on that.  My understanding is : when we select classes, we highlight  those area. The highlight style overwrite the existing style.

**Comment by Tasilee** [comment]
@qifeng-bai : True but if we de-select any selected class, you must be able to then select polygon style. Currently you can't change the style. Example: map a contextual layer, select a class, de-select the class, then try selecting polygon style.

**Comment by qifeng-bai** [comment]
@Tasilee which layer are you using for test?  I am using IBRA7 subregions as test. Tried to outline/filled style and select/deselect some regions. This layer works well

**Comment by Tasilee** [comment]
Hmm, seems to be working ok today. No idea what happened yesterday but I couldn't get the style to change after class selection/de-selection. 

I did however note that you can't page the legend classes today :) Another issue. E.g., can't get to Victoria class.

**Comment by qifeng-bai** [comment]
@Tasilee Hm, pagination stops working. I will let you know when it is fixed. Thanks
