### ISSUE TITLE
multiple selection lists not working

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#258]
**Describe the bug**
spatial-service tools that use multiple selection lists do not work.

**To Reproduce**
1. Create a spatial-service tool that uses input type=list and constraints.selection=multiple.
2. Open this tool in spatial-hub.
3. The list does not appear.

**Expected behavior**
The list is expected to appear, allow multiple selections, and to send the selected values when the tool is executed.

**Actual behavior**
The list does not appear.

**Additional context**
This is required to support area report changes in https://github.com/AtlasOfLivingAustralia/spatial-service/commit/cecc13f9ed6cf146b7aa03b05931b0d322cff714

**Comment by Tasilee** [comment]
Nice strategy.

Suggest in the case of the Area report - PDF, and maybe others, that the default scenario is a 'Pages to Include' and a 'Select all' set as default, and a 'Deselect all' option.

**Comment by Tasilee** [comment]
PS: Area report is hanging on "preparing"
