### ISSUE TITLE
SP defined species lists should request true list type

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#263]
**Describe the bug**
One of the standard species list TYPEs includes "Spatial Portal defined list" which gives no indication of the true list type.

**To Reproduce**
1. Go to **Add to map | species |  Create new species list**
1. There is no option to nominate list type (and this list should not include "Spatial Portal defined list" 

**Expected behavior**
Need a drop down box in dialogue window that includes species list type
![Capture](https://user-images.githubusercontent.com/6656350/66169450-c8792e80-e683-11e9-80d3-278e24368ed9.jpg)

**Comment by Tasilee** [comment]
The List type is being requested in the Spatial Portal but is NOT being registered in https://lists.ala.org.au. For example a "Test" lost turns up in Lists as "Spatial Portal defined list" still.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/a072c0e57c33e479691e2181794f92a2d402d5f4
