### ISSUE TITLE
Unrealiable BCCVL exports

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#268]
**Describe the bug**
Report from a user on support desk that:

```
Exports to the BCCVL, when they finished, were often reported by the BCCVL as incomplete zip files.
```

**To Reproduce**
1. Go to ticket 42638 in Helpdesk for the details of what they were doing and correspond with the user directly about their requirements.

**Expected behavior**
BCCVL should not report incomplete zip files.

**Actual behavior**
BCCVL are reporting incomplete zip files.

**Additional context**

**Comment by adam-collins** [comment]
biocache-service download webservices related
