### ISSUE TITLE
Add to Map | Facet - Search hanging

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#272]
**Describe the bug**
Add to Map | Facet - search for any facet term and it hangs forever

**To Reproduce**
1. Go to 'Add to Map | Facet'
2. Click on 'Facet begins with (case sensitive):..."
3. Enter say "sampling" and click on 'Apply filter'

**Expected behavior**
The search should quickly return matched terms.

**Actual behavior**
Hangs

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6656350/69383911-0521e780-0d0f-11ea-8ecc-0e15bdd78d16.jpg)

**Comment by adam-collins** [comment]
Sometimes slow.
