### ISSUE TITLE
WKT import needs test for validity and a fix if possible

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#274]
**Describe the bug**
A user entered "POLYGON ((141.0 -33.0, 141.0 -32.12, 143.25 -32.12, 143.25 -33.0, 141.0
-33.0)) and this is valid as far as I can tell. But the import misinterpreted it such that it assumed the area OUTSIDE this polygon, not inside as you would expect.

**To Reproduce**
1. Go to 'Add to Map | Area | Enter area coordinates (WKT)
1. Enter POLYGON ((141.0 -33.0, 141.0 -32.12, 143.25 -32.12, 143.25 -33.0, 141.0 -33.0))
1. The area draws correctly, but is misinterpreted if you run Tools | Area report

**Expected behavior**
The coordinates are ok, just entered anticlockwise. If you enter the same coordinates clockwise, it works fine.

**Actual behavior**
Polygon area is outside, not inside as you would expect.

**Additional context**
We need to check the 'validity' of the WKT and adapt if possible rather than plot correctly but define incorrectly (strange as it sounds). In short, it should not matter which way coordinates are entered as long as they are either clockwise or anticlockwise.

**Comment by Tasilee** [comment]
Re-tested. Generated a small Add to Map | Area | Draw bounding box, exported it as WKT and tried to Import it as WKT and it didn't do anything. This suggests a more general failure.

**Comment by adam-collins** [comment]
Released in 0.3.4
