### ISSUE TITLE
Hide and/or disable Scatterplot functionality

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#277]
The Scatterplot functionality has been disabled on the biocache-ws.ala.org.au and biocache-ws-test.ala.org.au sites due to performance issues until a biocache-service developer is assigned and available to work on improving it. The Scatterplot functionality in the spatial portal needs to be disabled to avoid users attempting to use it. It would also benefit the spatial portal maintainers by avoiding File Descriptor leaks due to spatial portal not closing its file descriptor handles promptly and retrying an excessive number of times when the fixed failure message comes back from biocache service when calls are made to the Scatterplot service.

**Comment by Tasilee** [comment]
Disabling one of the basic SP functions that was working fine seems extremely odd to me. I just tried it with a single species (1807 records) and it simply hangs. This is totally unacceptable. At the minimum, a  warning needs to be provided, rather than leaving users in limbo.

**Comment by ansell** [comment]
Feel free to mention to the ALA Management that biocache-service needs a developer
