### ISSUE TITLE
Report on Spatial Portal usage

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#278]
@Tasilee commented on [Thu Feb 06 2020](https://github.com/AtlasOfLivingAustralia/spatial-portal/issues/167)

We do not have an ability to produce a report of Spatial Portal usage. At this time, when my position is being replaced, it will be important to review usage to assist in setting priorities for addressing outstanding issues and plotting a pathway ahead. Ideally, the report should produce a CSV file as per attached template.
[Spatial Portal User report.xlsx](https://github.com/AtlasOfLivingAustralia/spatial-portal/files/4162158/Spatial.Portal.User.report.xlsx)
 
Todo:
[https://github.com/AtlasOfLivingAustralia/spatial-service/blob/master/grails-app/controllers/au/org/ala/spatial/service/ReportController.groovy](ReprotController)
1, Support pass date ranges
2, Strip off user name / email  from user based report

**Comment by nickdos** [comment]
For DQ project report - Bai is looking to see if there is a service we can use to put togther a quick report (maybe using Data Studio).

@Rita-C & @CorinnaPaeper - FYI this might be a candidate for a Data Studio report that is  easy to find for LT (for Lee's report above).

**Comment by qifeng-bai** [comment]
We can pull info from task table directly, but it only has user_id . We need to pull out user info from Auth as well.

**Comment by qifeng-bai** [comment]
select user_id, name,count('name'), count('user_id') from task where user_id !='null' group by name, user_id order by user_id, name ;
//Select top 20 users.
select user_id, count('user_id') as totalUsage from task where user_id !='null'  group by user_id  ORDER BY totalUsage DESC limit 20 ;

//return top 20 users' usages 
select user_id, name, count('name'), count('user_id') from task where user_id in (select user_id from task where user_id !='null'  group by user_id  ORDER BY count('user_id') DESC limit 20 ) group by name, user_id order by user_id, name ;

psql command:
\copy (select user_id, name, count('name'), count('user_id') from task where user_id in (select user_id from task where user_id !='null'  group by user_id  ORDER BY count('user_id') DESC limit 20 ) group by name, user_id order by user_id, name) to ./sp_report.csv WITH CSV

//cp report to local
scp aws-spatial-prod.ala.org.au:/tmp/sp_report.csv ./

Example:
[sp_report.txt](https://github.com/AtlasOfLivingAustralia/spatial-hub/files/4184018/sp_report.txt)

**Comment by nickdos** [comment]
@M-Nicholls did you see the attached `txt` file above. Is this enough info or do you need a longer list of userIDs?

**Comment by qifeng-bai** [comment]
@nickdos I needs to reconstruct the data to the format Lee wants

**Comment by Rita-C** [comment]
@qifeng-bai , can the .csv be generated by a webservice call? 
We have a data studio report based on webservice call "https://biocache-ws.ala.org.au/ws/occurrences/facets/download...." The report is dynamic and anyone who has the report Url can access the report. @nickdos this is the top data provider DS report.

**Comment by nickdos** [comment]
@qifeng-bai used SQL for that dump but there might be some web services sitting over those tables? Otherwise that would be a small task to create web services we could use to populate some usage reports in Data Studio.

**Comment by qifeng-bai** [comment]
@nickdos  I am not aware of any similar web services exist before, I am building  a report webservice and adding few lines to generate CSV like this
![Screen Shot 2020-02-12 at 10 31 00 am](https://user-images.githubusercontent.com/31238531/74289389-0cdbb000-4d83-11ea-9b2e-d565ac6ccc72.png)

**Comment by Tasilee** [comment]
Getting close. Can we add names instead of the userids, and email addresses :)? If we can also add the primary/secondary user types from the user profiles we could do a proper analysis of how the current terms relate or don't (need different terms).  I can use such a report to classify users into useful categories.

**Comment by qifeng-bai** [comment]
@Tasilee Do you need  all users usage report, or the report for the most frequent users, like top 10, 20
or other constraints, like in recent 6 months, 12 months as such?

**Comment by Tasilee** [comment]
From what @adam-collins said, the new SP limits the report to the last year or so, and this must be ok I guess. Regards top X users, I'd prefer to see all users of the SP so that we can get a comprehensive view of who is using what. I know it will be a 'long tail' (many users using limited SP options once), but even that would be useful as we can see what options they are using. My guess would be be "Add to Map | Species ...". I am not even sure how we would identify the 'top' users, but probably the best option is summing usage events across all of the columns (functions/options). Also, with all users, I can take the CSV file and run a classification over it to produce an image of user-types. This would be extremely useful to assist prioritization, including identifying gaps.

**Comment by CorinnaPaeper** [comment]
Trying to set this up as a Data Studio report would be good as we can add it to the collection of reports we already have. We have a few use cases that use Google Sheets as a data source already, so we can possibly set this up in a similar way.

**Comment by qifeng-bai** [comment]
@Tasilee Like this. Any info you need?
![Screen Shot 2020-02-12 at 1 55 29 pm](https://user-images.githubusercontent.com/31238531/74298995-78337b00-4d9f-11ea-9d6d-20c814c29169.png)

**Comment by Tasilee** [comment]
Thanks @qifeng-bai. Very close. Looking good. Two issues--

1. "Role" is replaced by the two columns as in the user profile (e.g., for me: primaryUserType = 
Ecological research; secondaryUserType = Spatial analyses)

1. I presume the report column of functions used, covers what I had in the spreadsheet https://github.com/AtlasOfLivingAustralia/spatial-portal/files/4162158/Spatial.Portal.User.report.xlsx

**Comment by qifeng-bai** [comment]
@Tasilee  User type has been fixed. Current reports only includes 'Tools->',  does not include others. 
@adam-collins  Do we keep records of user behaviours, such as 'adding species'
Here is the current report from Prod. I renamed it to txt for uploading
You can use Excel to open it, after rename it back to CSV


[report (2).csv.txt](https://github.com/AtlasOfLivingAustralia/spatial-hub/files/4189847/report.2.csv.txt)

**Comment by Tasilee** [comment]
Nice work @qifeng-bai. That looks ideal and already tells us a fair bit.

@adam-collins tells me that the other functions (add to map, import, export) are logged so we should be able to extract the info.

Can't figure out why userId 77145 doesn't have a name and I can't look them up via https://auth.ala.org.au/userdetails/admin/user/list (which we should be able to use the userId in the search). Ditto for 

68898
83069
85155
83062
83063
83070
83068
83067
91754
83061
74510
83064
84878
77331
81352
85126
55841

First review observation: The user profiles (if correct) says that 79% of users listed have no primaryUserType. We need to do something about that at some point.

Can we add email addresses and organization? :)  I'm asking a lot I know, but this is starting to be a very neat report!

**Comment by nickdos** [comment]
@Tasilee we got rid of the `primaryUserType` and `secondaryUserType` from the register form. They were previously optional and most users left them blank and in this modern age of privacy awareness, most users do NOT want to disclose that information about themselves. The UI on the older form for those fields was terrible as it required you to use autocomplete to "guess" what the available options were, so another reason we ditched it.

https://auth.ala.org.au/userdetails/registration/createAccount

**Comment by Tasilee** [comment]
Thanks @nickdos, that would account for it!

I guess I can 'reverse engineer' at least a key category from the report data. This also suggests that the 'organization' will now be more significant, unless it too is mostly blank :)

**Comment by nickdos** [comment]
We should start seeing more `organisation` values, assuming more research-types are using AAF to login now, as we can get that automatically via AAF credentials. 

Also, email address domain could be another good source of organisation but only works if people use a work email address. 

You should talk to @CorinnaPaeper too - she can generate a list of organisations (or equiv) from Google Analytics ranked by most common to least commonly used on SP. It won't give you any breakdown by function but might be a handy augmentation.

**Comment by qifeng-bai** [comment]
@nickdos @Tasilee  It wont't be a problem to add email, org etc in .
@adam-collins  I assume logs about the tasks are in db, not in file system

**Comment by CorinnaPaeper** [comment]
Hi @qifeng-bai , Rita and I had a quick look at getting the data into a basic Data Studio report (just to get started). This is the data we are after - is this something you can get us via SQL? Ideally, we would like to get the data broken down by month (or quarter), is that possible? Also, we were thinking it might be good to exclude ALA staff from the counts?

![image](https://user-images.githubusercontent.com/35747214/74387616-1df0f380-4e4d-11ea-93c4-576e74aa7ce1.png)

**Comment by qifeng-bai** [comment]
@CorinnaPaeper Yes, I can. But it will be another report csv file.

**Comment by Rita-C** [comment]
Can you make it another sheet rather than a new file @qifeng-bai ? We would like a webservice call to retrieve the .csv later.

**Comment by qifeng-bai** [comment]
@Tasilee 
It is 1.5M size, and took few minutes to generate. 
It also contain some 'WRONGS' tasks:   
  Column G  -   'null',   
  Last few columns are 'HTTP error'.   
They need to be manually removed

<img width="815" alt="Screen Shot 2020-02-13 at 11 21 41 am" src="https://user-images.githubusercontent.com/31238531/74389752-54ca0800-4e53-11ea-9436-387534ba939c.png">


[report.csv.txt](https://github.com/AtlasOfLivingAustralia/spatial-hub/files/4195885/report.csv.txt)

**Comment by qifeng-bai** [comment]
@CorinnaPaeper  When you said "broke by month", I am assuming 'broke by Year and Month', Is that correct?
Ruling out task from ALA member,  need more steps to do

**Comment by CorinnaPaeper** [comment]
@qifeng-bai , yes, by year and month if there is data for multiple years available. It would enable us to do a bit of trendline analysis on the data. Is there anything I can do to help re filtering out ALA staff member data (e.g., collating a list of all userID belonging to ALA staff)?

**Comment by qifeng-bai** [comment]
@CorinnaPaeper  If you can find an ID list of ALA staff, that would be very helpful. I happened to find our ALA member uses CSIRO as org

**Comment by qifeng-bai** [comment]
@CorinnaPaeper  Are your Data studio able to handle this format
[task_based_report.csv.txt](https://github.com/AtlasOfLivingAustralia/spatial-hub/files/4196452/task_based_report.csv.txt)
<img width="530" alt="Screen Shot 2020-02-13 at 3 14 01 pm" src="https://user-images.githubusercontent.com/31238531/74400901-99fe3200-4e73-11ea-9a32-626efd5ce397.png">

**Comment by Tasilee** [comment]
Thanks @bai! That report above on users by activities is wonderful! I think @M-Nicholls  and I can probably figure some names for his committee and the data will enable me to do an analysis of both users types and function usage.

I am however having troubles interpreting the meaning of some of the column headers of the functions. Can you create a simple table (csv will do)  of two columns - 

Column 1: Term, Column 2: Definition

For example, I am unsure what "Map species by layer" or "Map session" are...and there are plenty others. 

Also: Are some of the columns the sum of others?

**Comment by qifeng-bai** [comment]
@Tasilee  "Map species by layer" , "Map session"  those are function names run by users and  recorded in our Log system.  I am not sure what they actually did.  @adam-collins  may be the best person knows what these actions are about

**Comment by Tasilee** [comment]
Thanks @qifeng-bai. I'll check with Adam.

**Comment by Tasilee** [comment]
BTW, I don't know why GDM is still being reported as it has been disabled for over a year. Another question for @adam-collins

**Comment by Tasilee** [comment]
What is the status of this issue? 

I have a CSV file that was edited by Adam that clarifies the actions/tools ('person x actions'). I will include this my March report to Andre and have summarized the findings from it. 

Has there been anything more done regarding 'person x actions' and 'action x usage'? The report probably needs to be standardized and run at least annually.

**Comment by qifeng-bai** [comment]
@Tasilee my best guess is because the report was generated based on history logs, so if gdm has been run , then it will be in the report

**Comment by Tasilee** [comment]
I suggest we need two reports: The first requests a date range and reports actions x number of uses (across all users) in that period. The second requests a date range and reports users x actions with number of uses as content. Both reports need to be managed by someone and run on demand, and once for each year. Who?

**Comment by CorinnaPaeper** [comment]
As per the much earlier discussion, we still might be able to manage this as an on-demand report via a Data Studio report. I think @Rita-C was looking into getting the data pulled in.

**Comment by nickdos** [comment]
@qifeng-bai its not clear from the comments in this issue whether the report files you have included are from a one-off export job or if there is an admin page (or web service) on the server that a user (ROLE_ADMIN) can go and get the latest version. I think Lee wants the latter although the issue was not specific in asking for this.

**Comment by qifeng-bai** [comment]
@nickdos @Tasilee  Report generator has been deployed for testing. We can generate user report via 'https://nectar-spatial-test.ala.org.au/ws/report/', [Test server does not have many data]
task based report via '/ws/report/task'
Code is in dev and master branch, waiting for @adam-collins review.  And may also need to add authenticating steps as well. 

The last two reports were generated from my local dev environment  connecting prod database

**Comment by Tasilee** [comment]
Thanks @qifeng-bai. We should also have a reference somewhere, probably in Confluence (?) with a link and some details as to parameters, output etc.

**Comment by nickdos** [comment]
@qifeng-bai I think there should be a link to the CSV report on the https://nectar-spatial-test.ala.org.au/ws/ page, under Admin Tools section.

**Comment by qifeng-bai** [comment]
@Tasilee At this moment, user report does not support  date range , but definitely we can add params like 'from=xxxxx&to=xxxx' .  Do you want me add this function in?
@nickdos I suspect SS has admin page

**Comment by Tasilee** [comment]
Thanks @qifeng-bai. We probably need a short tele-discussion with @nickdos, @CorinnaPaeper, @Rita-C , @adam-collins and I (and ???), as soon as practical.  It would be good to nail this reporting down now that it has been largely done. We need to be coordinated and consistent. That said, the Spatial Portal is probably an outlier given the number of functions. That said, the common dimensions are user, function and time period.
