### ISSUE TITLE
Predict (Maxent) legend broken

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#280]
**Describe the bug**
MaxEnt runs and the resulting map and MaxEnt output is fine but the SP legend of the MaxEnt pseudo probabilities is broken.

**To Reproduce**
1. Zoom/pan map to Tasmanian extent
1. Go to **Tools | predict**
1. Use **Eucalyptus gunnii** and **Current extent** with **Williams Best 5 layers** and **5% jacknife**
1. Run it
1. Examine legend: missing

**Expected behavior**
A legend with (pseudo) probabilities

**Actual behavior**
Broken image for legend

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6656350/74701880-60a33900-525c-11ea-92a9-ae43e9b5d616.jpg)

**Comment by qifeng-bai** [comment]
@adam-collins seems  https://spatial.ala.org.au/geoserver/wms?layer=ALA:596861_species  failed, but 586861_species exists under /data/spatial-data/layer

**Comment by qifeng-bai** [comment]
Line 682 in mapService.js,  add ->  newLayer,    url: layer.layer.displayPath   seems not correct

**Comment by Tasilee** [comment]
Duplicate of #256
