### ISSUE TITLE
Click on map later doesn't display class/value

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#281]
**Describe the bug**
You can identify the class or value of layers under the cursor by a mouse click. This isn't working

**To Reproduce**
1. Go to 'Add to Map | Layer' and select any layer
1. Zoom/pan to area of interest and click on the map
1. No pop-up

**Expected behavior**
A pop-up with values at that point of the displayed layers.

**Actual behavior**
No pop-up on click.

**Comment by qifeng-bai** [comment]
![Screen Shot 2020-02-19 at 10 10 57 am](https://user-images.githubusercontent.com/31238531/74786190-2c815400-5300-11ea-9a83-f91a96a57b43.png)
Pop-up displays when the added layer is clicked

**Comment by Tasilee** [comment]
Seems to be working now. No idea why it wasn't an hour or two ago.

**Comment by Tasilee** [comment]
Ah, I happened to pick a layer that it doesn't seem to work on: Tenure of Australia's Forests (2013). I wonder then about others?

**Comment by qifeng-bai** [comment]
Fixed
