### ISSUE TITLE
New point layer from facet duplicates facet used

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#284]
**Describe the bug**
When a new species layer is created from the facet 'coordinate uncertainty in metres', the new layer has this facet duplicated in the legend.

**To Reproduce**
1. Go to 'Add to Map | Species'
1. Map a species with > 1000 records
1.  Go to the facets in the legend and select 'Coordinate uncertainty (in metres)'
1.  Select one class and then click on 'Create new layer with selection'
1. Click on the new layer in the layers table
1. Look at the facets in the legend and see that 'Coordinate uncertainty (in metres)' is duplicated.

**Expected behavior**
Legend facets should not be duplicated.

**Actual behavior**
New layer has duplication of selected facet

**Screenshots**
![image](https://user-images.githubusercontent.com/6656350/75930235-42794200-5ec6-11ea-9a0b-0944f152bd52.png)

**Comment by adam-collins** [comment]
Released in 0.3.4
