### ISSUE TITLE
Add distance measuring tool

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#286]
**Is your feature request related to a problem? Please describe.**
We have had a number of requests to be able to measure distances between two points on the map. The most recent request was from an environmental consultant on March 24. It is a reasonable request as such a tool could be used for a wide range of functions. For example, determining distance of a sighting from a road, the distance between two sightings, the distance between a boundary and a sighting etc.

**Describe the solution you'd like**
The solution that would add some nice additional functionality would be to use Add to Map | Area | linear buffer and to use a dynamic readout on screen of the line length. You would click and hold on a point on the map and drag the mouse to another point - while dragging, an on-screen readout of the distance in metres, when the button is released, a line is drawn and a buffer area is filled in.

**Describe alternatives you've considered**
A specific tool on the map window - maybe an icon under the zoom bar. A line is drawn on drag but dissapear when mouse button is released, but distance remain on screen with delete icon.

**Additional context**

**Comment by adam-collins** [comment]
Release in 0.3.4
