### ISSUE TITLE
Add to Map | Species not mapping points

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#288]
**Describe the bug**
Some species are not mapping points and when zoomed to extent, resolve to lat/lon 0,0.

**To Reproduce**
1. Go to 'Add to Map | Species | Anabaena crassa 
1. Click on zoom to extent icon
1. See error: No point platted and area is zoomed into 0,0. When the same species is mapped in biocache.ala.org.au, the records display in Australia. If the records are then 'View interactive map', they are displayed in the Spatial Portal. BTW, this button should, for consistency say "View in Spatial Portal".

**Expected behavior**
Any species with occurrence records and lat/lon should map in the SP. This is the most basic SP function! is there something odd about the species in the example?

**Actual behavior**
No points are mapped

**Screenshots**

**Comment by timhicks-ala** [comment]
Additionally reported in helpdesk ticket 81339. Found a work-around for this user where adding any filter at all in Biocache (including ones that do not filter out any actual records) and then attempting to view in spatial portal will work.

**Comment by timhicks-ala** [comment]
Additionally reported in helpdesk ticket 81457.

**Comment by Tasilee** [comment]
Tested on spatial-test using example: Works well. (but it did take about 50 seconds to map points).
