### ISSUE TITLE
Adjust default settings to improve UX

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#290]
Helpdesk ticket 79557 has suggested some improvements to Spatial Portal UX around default values for certain options:

1. When adding a Species, all three options under "Include related areas" are ticked by default:
- Include Expert Distribution areas
- Include Animal Movement Data
- Include Checklist areas

Exactly what these are is not clearly defined at that point, and can affect the analysis in unpredictable ways if you are unfamiliar with them. It may be best to have these turned off by default, and/or to include info boxes describing their functions.

2. When exporting points, the are defaults to "Current extent", which is at odds with the default for adding species, which is "World". This is inconsistent and exporting points should default to "World" as well.

**Comment by Tasilee** [comment]
Thanks @timhicks-ala . I spotted this one this morning: Useful feedback. I'll discuss with Adam (e.g., how case dependent is it) and see what we can do. I think we may be able to make some of these changes fairly easily in the config file. The usual hassle is priority amongst all the other tasks :)

**Comment by Tasilee** [comment]
Tested on spatial-test: OK

Include Expert Distribution areas, Include Animal Movement Data and Include Checklist areas: 
No longer ticked by default.

When exporting points, the default now is "World" to match Add to Map | Species default.

**Comment by Tasilee** [comment]
Tested OK on Prod.
