### ISSUE TITLE
Spatial Portal fails to interpret biocache queries including brackets

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#291]
Raised in helpdesk issue 79592.

When moving a query from Biocache to the Spatial Portal, if the query URL includes () brackets, SP fails to fully load, perpetually showing the loading bar.

Example search: https://avh.ala.org.au/occurrences/search?q=%28collector_text%3AJeanes+AND+%28record_number%3A1653+OR+record_number%3A2129+OR+record_number%3A1651+OR+record_number%3A2550+OR+record_number%3A2326+OR+record_number%3A1687+OR+record_number%3A2146+OR+record_number%3A2357+OR+record_number%3A2349+OR+record_number%3A2337+OR+record_number%3A1858+OR+record_number%3A1869+OR+record_number%3A2381+OR+record_number%3A2555+OR+record_number%3A2627+OR+record_number%3A2123%29%29+OR+%28collector_text%3AWalsh+AND+%28record_number%3A6404+OR+record_number%3A6423%29%29&qc=data_hub_uid%3Adh9&fq=collection_uid%3A%22co55%22#tab_mapView

Clicking "View in spatial portal" shows the issue.

URL-encoding brackets as %28 and %29 makes no difference. The issue is not the length of the query URL.

Downloading the records via biocache and then importing into Spatial Portal as a point is a workaround.

**Comment by Tasilee** [comment]
Tested on spatial-test: Works with example above and variants: Works well.

**Comment by Tasilee** [comment]
Tests OK on production.
