### ISSUE TITLE
Select filetype dropdown is empty in Export Area

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/spatial-hub#292]
**Describe the bug**
Select filetype dropdown is empty in Export Area

**To Reproduce**
1. Go to 'Export - > Export areas.'
2. Click on 'Filetype' drop down 
3. Verify that is not empty
4. Click on Define area
5. Choose an option (Draw bounding box is the easiest)
6. Follow prompts until you return to Export areas pop up.
7. Click on 'Filetype' drop down 

**Expected behavior**
You can select any option

**Actual behavior**
Dropdown is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/8326394/82276922-f8cecc80-99c9-11ea-886b-1271d2b15459.png)

**Comment by javier-molina** [comment]
Reported on https://support.ehelp.edu.au/a/tickets/80561 

Workaround suggested by Adam:

> adamcollins  13:40
> Unknown bug. Workaround is to use ‘Add to Map’ | ‘Area’ to create the area before using ‘Export’ | ‘Areas’

**Comment by Tasilee** [comment]
This appears to be a momentary aberration. I have noted it myself on rare occasions but a refresh seems to work.
![Capture](https://user-images.githubusercontent.com/6656350/82281936-f6726f80-99d5-11ea-8494-4ea4d4eefff4.jpg)

**Comment by adam-collins** [comment]
Released in 0.3.4
