### ISSUE TITLE
Add filtering tool to Add to Map | Facet

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#293]
**Is your feature request related to a problem? Please describe.**
We have the filtering tool available via Add to Map | Species but not Add to Map | Facet. It should be consistent.

**Describe the solution you'd like**
A method of of selecting multiple facet classes to filter all records to a set with the provided values.

**Describe alternatives you've considered**
There aren't alternatives when starting from the complete record database

Ideally for 0.3.3 release?

**Comment by Tasilee** [comment]
Tested on spatial-test: Selected two facets (habitat and sampling protocol) and Next button is not highlighted as no classes selected. We probably need to make this more obvious.

'Clear filter' doesn't seem to. You have to go back into the search and untick them. Even so, any classes previously displayed seem to remain.

With long lists of classes, at some point we need a way of popping up a longer list (few pages).

But once you get the hang of it, it works.

**Comment by adam-collins** [comment]
Released in 0.3.4

**Comment by Tasilee** [comment]
Clear selection button doesn't work.

**Comment by Tasilee** [comment]
Filtering doesn't work - a priority as picking classes from multiple page lists is impossible once beyond about 10.

Also, it would be useful to have the alpha sort option here that we do on the legend classes.

**Comment by nickdos** [comment]
@adam-collins add commit link. 

Also some clues for testing.

**Comment by adam-collins** [comment]
Issue details:
- Add To Map
- Facets
- Select a facet from the dropdown
- Attempt to filter with some text (not working, list should be filtered)
- Use checkbox to select one or more records
- Clicking 'clear selection' button removes the selection (now working)
- No option to sort the list alphabetically

Sorting and Filtering is not working. This may require work in biocache-service.

**Comment by qifeng-bai** [comment]
@adam-collins  Biocache query returns results ordered by count.  Do we really need the function  to sort results alphabetically ?

**Comment by Tasilee** [comment]
Yes, as sometime (often?) there are so many classes and you need to find where it is

**Comment by qifeng-bai** [comment]
@Tasilee I am implementing sorting function

**Comment by nickdos** [comment]
@qifeng-bai the biocache-service API has a param to change sort order - see API docs

**Comment by qifeng-bai** [comment]
@Tasilee 
![Screen Shot 2020-11-20 at 1 12 33 pm](https://user-images.githubusercontent.com/31238531/99749201-1ecc5980-2b32-11eb-8c8b-56c35727ed3c.png)

![Screen Shot 2020-11-20 at 1 13 32 pm](https://user-images.githubusercontent.com/31238531/99749254-3acffb00-2b32-11eb-94f9-6dc4eb02adc8.png)
