### ISSUE TITLE
Unexpected mapping results from species query 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/spatial-hub#294]
**Describe the bug**
Spatial portal map returns strange behaviours given the same dataset from different origins.

Species in question = _Allocharopa tarravillensis_ 

**To Reproduce**

**In the Spatial Portal**
Add to Map | Species, click spatially suspect - 37 records appear, map zoomed to extent
Add to Map | Species, no click spatially suspect - only 1 record appears in NW Tas (in Deep Creek Bay in the water)

**From BIE**
https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:dfaae3f4-29e0-4e41-afed-cde7fcba8c2b#overview (map is fine)
Click View Interactive Map
https://spatial.ala.org.au/?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:dfaae3f4-29e0-4e41-afed-cde7fcba8c2b  -  No point platted and area is zoomed into 0,0
Reminiscent of https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/288 

**From Biocache**
https://biocache.ala.org.au/occurrences/search?q=qid%3A1591072310241#tab_mapView (map is fine)
Click View in Spatial Portal
https://spatial.ala.org.au/?q=qid:1591072310241 all records appear

Then in the download link on the SP: https://doi.ala.org.au/doi/10.26197/5ed744f3708e8
Only the 1 "spatially valid" record appears.

**Expected behavior**
The Spatial Portal should behave the same way regardless of the origin of the data? (eg biocache vs bie). Also should the download  reflect what's on the map?

**Additional context**
The Geospatial Kosher flag is changing overnight (biocache-store deploying now) and we're about to put out some comms about it; perhaps this issue will be quite visible.

**Comment by adam-collins** [comment]
Links to SP with `q=` are broken. This explains the result when arriving from BIE. That this works from Biocache when using a `qid` is due to how biocache-service works.

SP `Export | Points` has filter checkboxes in the `species` section. By default the filter applied will exclude `spatially suspect` occurrences. This results in the download with only 1 record.

**Comment by peggynewman** [comment]
To clarify:
1. If links to SP with q= are broken does that mean that there needs to be a fix to BIE?
2. I need to go back to the user and tell them that to use the Export | Points facility if they want to control the filters. Or should we be raising an issue to have the default download reflect what is on the current screen?

**Comment by Tasilee** [comment]
Tested on spatial-test: OK. I tested a few species both within the SP (spatially valid and suspect) and from biocache and it all matches.

**Comment by Tasilee** [comment]
Tests ok on production.
