### ISSUE TITLE
Compare points not working

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#296]
Compare points not working

**Comment by Tasilee** [comment]
It is reporting of against the subset of layers (which I know are available in spatial-test) but I think 6 of the layers still have missing intersects?

Second: Name of downloaded file is "nearestLocalities__.csv" and probably should either be generic "data" or "Point_compare.csv" or similar.

**Comment by Tasilee** [comment]
Tests OK on production.
