### ISSUE TITLE
Integrate biocollect sites, images,  and Add count of MERIT and BioCollect polygons intersecting with Area Reports

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#3]
Support biocollect data with Add to Map options for Area.

Allow the adding to map of biocollect site images.

@Tasilee comments:

| Field | Value |
| ----- | ----- |
| **Type** | Enhancement  |
| **Priority** | 7 |
| **Sprint** | 2 | 
| **Developer days** | 2 |
| **Admin days** | 0 |
| **Description** | Polygons from MERIT and BioCollect projects are available and should be reported  in Area Reports |
| **Epic** |  Efficient ecological analysis |
| **Theme Links** | Community data collection |
| **Community** | Research, management |

We used to have a POI (Points of Interest) component in the Tools | Area reports but this was lost. Given that all of the bioCollect and MERIT projects have a defined polygonal boundary, it is important to be able to locate any such projects within any user-defined area.

This is a perfect example of the need to ensure that ALA data is cross-linked wherever possible. While projects can be searched for by name from BioCollect and MERIT, the ability to search for projects by area is not. The Spatial Portal's area reports are aimed at informing users of all bio-related data within a user-defined area. Knowing that there are or were bio/management projects operating in an area is a significant dimension of practical information.

We would ideally add two more 'records' one for MERIT projects and one for BioCollect projects, with the number listed linked to table with project metadata with link to project details.

Adam and I have discussed this and we believe the following would add massive value to both Projects and reporting on areas. Exposure of AREAs of projects in two places-

Gazetteer polygon (Add to Map | Area | Gazetteer polygon - where name of polygon or Project can be found and mapped.
Area report - add an entry that is called "Projects" which lists the number of projects from MERIT/BioCollect that have an area which intersects with the target area. The Projects can be LISTED (maybe project name, project type with link to more details in MERIT/BioCollect) or MAPPED to map the project areas.

**Comment by adam-collins** [comment]
Moved from AtlasOfLivingAustralia/spatial-portal#5

**Comment by adam-collins** [comment]
CORS issue needs addressing

**Comment by nickdos** [comment]
@adam-collins suggests talking to @sbearcsiro about leveraging the Redis DB in AUTH for this functionality. Session key to be shared across all systems, to make this work.

Needed for CORS requests from SP to BioCollect (host gets stipped out - new browsers do this for security reasons).

**Comment by qifeng-bai** [comment]
Two issues: 
1, CORS prohabited by BioCollect
2, https://biocollect-test.ala.org.au/merit/nocas/geoService?max=0&geoSearchJSON={"type":"Polygon","coordinates":[[[147.268981933594,-42.4887292049423],[147.946014404297,-42.4887292049423],[147.946014404297,-42.0976333121904],[147.268981933594,-42.0976333121904],[147.268981933594,-42.4887292049423]]]}

This query failed.  Need to confirm with Merit team

**Comment by qifeng-bai** [comment]
@chrisala  mentioned: 
" Since MERIT doesn’t support those geo shape queries, I  suspect it was done deliberately via BioCollect using the MERIT hub. 
Temi mentioned there was a known bug though with those geo queries at a standup a while back I seem to remember "

**Comment by qifeng-bai** [comment]
Waiting Biocollect to fix
