### ISSUE TITLE
Area report - round Area sq km to 1 decimal place

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#30]
Currently we are getting a slider as the area is reported to 13 decimal places. Please round to one decimal place (100sqm). It would be good to have this addressed prior to 29/9 as I'll be workshopping area reports to LGA this day.

![capture](https://cloud.githubusercontent.com/assets/6656350/18454376/3929a4ce-7987-11e6-857a-69aa63fc6b19.jpg)

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
Nice.
