### ISSUE TITLE
The CAPAD layers not displayed in Add to Map | layers with filter

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#304]
**Describe the bug**
When doing Add to Map | Layer, I enter "CAPAD" in the search box and none of the CAPAD layers are displayed.

**To Reproduce**
1. Go to 'Add to Map | Layers'
1. Click on search box and enter "CAPAD"
1.  See error: None of the CAPAD layers are displayed.

**Expected behavior**
CAPAD layers should be displayed on relevant filter

**Comment by adam-collins** [comment]
Released in 0.3.4
