### ISSUE TITLE
Create layer without selection not working

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#307]
**Describe the bug**
After selection of facet classes, clicking on "Create layer without election" does nothing

**To Reproduce**
1. Go to 'Add to map | Species | Eucalyptus gunnii' with defaults
1. Click on Facet dropdown and select a facet
1. Click on one or more classes
1. Click on 'Create layer without selection'
1. Nothing happens

**Expected behavior**
A new layer should be created that doesn't have the selected classes.

**Actual behavior**
Nothing happens

**Comment by adam-collins** [comment]
Released in 0.3.4
