### ISSUE TITLE
Add species, restrict to area feature ignores area bounds and adds records as if World was selected

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#308]
**Describe the bug**
When adding a species restricted to an area defined by an uploaded shapefile or KML, the "Restrict to area" option ignores the added area (which is selected by default) and instead adds occurrences as if "World" was selected.

This does not appear to affect inbuilt areas such as gazetteer polygons.

**To Reproduce**
1. Add area by uploading a shapefile
2. Add species, which by default restricts to the area

**Expected behavior**
Only occurrence records within the area should be loaded.

**Actual behavior**
Matching occurrence records from across the world are loaded instead.

**Screenshots**
![SP not restricted to area](https://user-images.githubusercontent.com/57081387/84956637-fc768000-b13c-11ea-90ce-e420962c0202.PNG)

**Additional context**

**Comment by timhicks-ala** [comment]
Issue raised in helpdesk ticket 82236

**Comment by adam-collins** [comment]
Released in 0.3.4
