### ISSUE TITLE
Add to map | Species has lost 'Lifeform' input option

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#319]
**Describe the bug**
Until recently, 'Lifeform' was an option for Add to map | Species, but appears missing now.

**To Reproduce**
1. Go to Add to map | Species
1. No Lifeform as input option.

**Expected behavior**
Lifeform radio button that produced a drop-down list of lifeform options to check (radio buttons)

**Actual behavior**
No lifeform option.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6656350/85237725-61e3ad00-b46c-11ea-8c78-87d192e8db82.jpg)

**Comment by adam-collins** [comment]
Released in 0.3.4
