### ISSUE TITLE
Scatterplot - single: environmental envelope must be mapped as lowest layer

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#320]
**Describe the bug**
When you select points on the scatterplot, this is the same process as using 'Add to map | Area | Environmental envelope' to map the area defined within the lower and upper bounds of the two selected variables/layers. The area that is mapped is however mapped over the point layer obscuring the points and highlighting. 

**To Reproduce**
1. Go to 'Tools | Scatterplot - single'
1. Select World, Banksia marginata, output environmental domain grid, Bio01 and Bio12
1. On scatterplot, select an area by clicking and dragging mouse over area
1. The environmental envelope area is drawn and points under it are highlighted but are hard to detect.

**Expected behavior**
When the environmental envelope is drawn, it should have the lowest display priority (equivalent to the lowest layer in layers table).

Ideally in the future, when an envelope is visible, a button that says create area would be nice.

**Actual behavior**
Environmental layer overwrites point layer and highlighting.

**Screenshots**
![Capture_2](https://user-images.githubusercontent.com/6656350/85242294-02909780-b482-11ea-8cbe-974917f38cca.jpg)

**Comment by adam-collins** [comment]
Released in 0.3.4
