### ISSUE TITLE
Add qid (maybe download link?) to point layer metadata

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#33]
As a first easy step to closer SP-BCCvL integration, could a qid be added to the metadata pop-up page for point layers? Maybe also as a canned search and canned download (reasonid=ecology)?

I can then get BCCvL developers to accept a qid

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
Beaut!
