### ISSUE TITLE
Can't delete a Saved SP Session

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#331]
**Describe the bug**
Clicking on the bin icon to the left of a saved session doesn't delete the entry

**To Reproduce**
1. Go to SP
1. Click on Load (top right)
1. Click on bin icon next to a session
1. Nothing happens

**Expected behavior**
If you have saved sessions, you need to be able to delete them after they are no longer required.

**Actual behavior**
Nothing happens when click on bin icon
![Capture](https://user-images.githubusercontent.com/6656350/86544282-e81dea00-bf68-11ea-9156-35f1e1db26df.jpg)

**Comment by nickdos** [comment]
@adam-collins add commit link pls

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/63b31e27c85e76797fd3567ad440cca63d4f40db

**Comment by qifeng-bai** [comment]
Not working. Will track this bug
