### ISSUE TITLE
Creating an area from an environmental envelope fails

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#334]
**Describe the bug**
Creating an area from an environmental envelope fails. The task appears to succeed but the Next button never becomes available and clicking Cancel returns to the map with no new areas created.

**To Reproduce**
1. Add area -> define environmental envelope -> Next
2. User's use case: layer is "precipitation - driest month", minimum 42, maximum 62 -> Next
3. Job runs and quickly finishes. Next button is unavailable. Spatial portal tasks show job finished (not failed).

**Expected behavior**
An area should be added to the SP with the above parameters.

**Actual behavior**
No area is created.

**Screenshots**
![SP environmental envelope](https://user-images.githubusercontent.com/57081387/86675094-af4f4500-c03c-11ea-8e20-b5fea3b0c355.jpg)

**Additional context**
Issue raised in helpdesk ticket 84863.

**Comment by qifeng-bai** [comment]
Duplicate with #398
