### ISSUE TITLE
Import points preview records is broken

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#336]
The preview records display is broken when used from the Spatial Portal to upload points, with angular errors in the console when using Firefox and Safari on MacOS. Note that the page is an iframe from sandbox, but it isn't broken when used on sandbox.

To replicate:

* Visit: https://spatial.ala.org.au/
* Choose `Import` -> `Points`
* Paste the following CSV file in:
```
decimalLatitude,decimalLongitude,scientificName,eventDate
142,-15,"Phascolarctos cinereus",2019-04-06
```
* Click `Check data`
* Observe the following screenshot with templates where the processed sample records are expected to be:
<img width="1285" alt="Screen Shot 2019-04-26 at 9 27 12 am" src="https://user-images.githubusercontent.com/82365/56774346-970f5380-6805-11e9-82b8-20c6a52deb21.png">

Discovered while testing ticket 31722 on helpdesk

**Comment by ansell** [comment]
I confirmed that this is still a bug on nectar-spatial-test today. Going through my support tickets and this appeared.

**Comment by Tasilee** [comment]
spatial-staging doesn't even get that far.

**Comment by ansell** [comment]
@Tasilee I haven't been following which versions are deployed to staging so far this week. Is it running the same version as nectar-spatial-test today?

**Comment by Tasilee** [comment]
Yes. I thought I'd check this on staging as I used that last night for a demo and noted that you mentioned that import | points failed on test.

**Comment by qifeng-bai** [comment]
Cannot reproduce this issue on firefox. The point was added to the map

![Screen Shot 2020-11-16 at 9 34 39 am](https://user-images.githubusercontent.com/31238531/99198802-ffaa9080-27ee-11eb-853c-3a67cb5006f4.png)

**Comment by ansell** [comment]
@qifeng-bai The issue is that the records cannot be previewed in the dialog box and I have confirmed that it is still showing the same behaviour today:

<img width="1555" alt="Screen Shot 2020-11-16 at 9 50 47 am" src="https://user-images.githubusercontent.com/82365/99199207-9b3d0080-27f1-11eb-9540-ca23c7bee2f3.png">

**Comment by qifeng-bai** [comment]
@ansell It even does not work on Chrome
