### ISSUE TITLE
Loading a saved session with a polygon doesn't display correctly

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#338]
When a session is saved in the Spatial Portal with a polygon defined, and then loaded later, it does not display correctly - the map shows entirely grey, and appears to be completely zoomed out. 

Example saved session that exhibits this behaviour: https://spatial.ala.org.au/?ss=1597112720961
Saved session with just a species added, which loads and displays correctly: https://spatial.ala.org.au/?ss=1597112415813

Additionally, the displayed mouseover coordinates are nonsense (eg. shows "NaN, 445.741").

As a workaround, clicking the magnifying glass next to the polygon or added species correctly zooms to extents, and restores the view.

Issue raised in helpdesk ticket 89944. Any additional reports will be recommended to use the workaround in the meantime.

![SP saved session blank](https://user-images.githubusercontent.com/57081387/89852203-b1736900-dbd1-11ea-9beb-eb36abc1dd93.png)

**Comment by timhicks-ala** [comment]
Additionally raised in helpdesk ticket 97920

**Comment by qifeng-bai** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-hub/pull/363

**Comment by qifeng-bai** [comment]
PR: https://github.com/AtlasOfLivingAustralia/spatial-hub/pull/370

**Comment by Tasilee** [comment]
Tested and it is working perfectly via URL and by Load session.
