### ISSUE TITLE
Feature request: Support for alternate projections

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-hub#34]
If possible, it would be great if it was relatively easy (config) to switch the map projection from spherical mercator to another projection. This would make adoption in other countries easier.
Im not sure of the full impact (in terms of dev time) of this enhancement so would be keen to hear thoughts.

**Comment by adam-collins** [comment]
For flexible projection
- Leaflet; looks like it will not be difficult to change the default projection. May need to use a plugin.
- Geoserver; other projections supported.
- Biocache-service WMS; might take a few days to add support for other projections.
- Basemaps; external base maps can be supported with options like mapproxy. Our outline base map that is delivered through our geoserver does not need this.

**Comment by adam-collins** [comment]
Update to progress

- Leaflet; Added a suitable plugin. Still need to:
    - Allow disabling of 'current extent' area option and some area creation drawing tools.
    - Update polygon splitting to also split across latitude wrapping at poles. 
    - Add option to limit map extents with projection configuration.
- Geoserver; Ready.
- Biocache-service WMS; GetMap requests are working. Other services altered have yet to be tested.
- Basemaps; Basemaps are now configurable for compatible projections. Use of OpenStreetMap is supported with a local deployment as WMS or as a Cascade WMS layer. 
- Spatial-service; Need to update MapImage process.
- Spatial-hub; Need to add projection selection to session save.

Openlayers has client side tile reprojection. As with Leaflet there are still tile errors near projection extents. Adding Openlayers as an option would be useful.
