### ISSUE TITLE
Contextual layer legend classes missing and selection mapping issues

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#344]
**Describe the bug**
Not all classes are displayed in legend table for some contextual layers such as the IGBP layer. Also, selecting/deselecting a visible class produces anomalous results on the map

**To Reproduce**
1. Go to Add to Map | Layer | IGBP
1. Note that only 5/17 classes are visible/accessible <> does nothing
1. Click on a class in the legend, deselect the class and select another class - not reflected on map

**Expected behavior**
All classes should be accessible, selectable/deslectable and mapped correctly.

**Actual behavior**
Not all classes are accessible or mapable. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/6656350/94378280-95209100-016b-11eb-997c-7bfcaba55690.jpg)

**Comment by adam-collins** [comment]
AtlasOfLivingAustralia/layers-store@a79749d

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/commit/24ca6b45e0865ab70e6af557652aad6bb2f76354

**Comment by qifeng-bai** [comment]
IGBP has filed ID:  cl1079a, which causes layer importing partial failed.

https://github.com/AtlasOfLivingAustralia/spatial-service/blob/master/grails-app/services/au/org/ala/spatial/service/ManageLayersService.groovy#L451  parsing field id to integer throws an exception
