### ISSUE TITLE
Difference between area reported by Import | Area and Tools | Area report

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#346]
**Describe the bug**
Two polygons in a shapefile were selected to be imported and merged as an area. The import table reported these as 26.1346Ha and 68.7258Ha (a total of 94.86Ha but the Area report listed 2.87sqkm (287Ha). One is wrong and it looks like the area report.

**To Reproduce**
1. Go to 'Import | Area and add Shapefile of #345
1. Select the two polygons in the table (visible) with the sizes as above
1. Click 'Next'
1. Click on Tools | Area report - interactive with the imported area
1. See anomaly

**Expected behavior**
The size of the areas should match
![Capture](https://user-images.githubusercontent.com/6656350/94776369-f8792000-0404-11eb-909b-7352ae5ffaab.jpg)
![Capture2](https://user-images.githubusercontent.com/6656350/94776386-fca53d80-0404-11eb-996c-9d75e3f886b9.jpg)

**Comment by qifeng-bai** [comment]
@Tasilee Can you pass me the SHP you are using please?

**Comment by qifeng-bai** [comment]
Below are some investigations:
I have update two features (0, 2) from Koppen.shp (EPSG 4326 ).   
The original koppen shp shows:  ~32536 sqm for featureIdx 0, and ~ 1946 sqm for featureIdx 2
**~34483 in total**

![Screen Shot 2021-03-09 at 3 48 02 pm](https://user-images.githubusercontent.com/31238531/110420660-e310cc00-80ef-11eb-9be0-72df1e2f75cb.png)

Both features (Polygons) were uploaded to PG successfully and rendered on Map

the_goem in PG is also correct,  two polygons are rendered in third party software.  

However, the record in PG has field: **area_km = ~33201**, I believe the value was calculated in uploading process ( Not match the total area from the origin SHP)

I also calculated areas with different CRS:
`SELECT ST_Area(the_geom::geography) sqm,  ST_Area(the_geom) area, ST_Area(st_transform(the_geom,3857)) sqm_3857, area_km
	FROM public.objects where pid='10268';`

None of them match the original total area.
 
Results:
![Screen Shot 2021-03-09 at 4 04 44 pm](https://user-images.githubusercontent.com/31238531/110421252-33d4f480-80f1-11eb-8ed3-10d857225b5d.png)

@Tasilee @adam-collins  I don't have adequate geospatial knowledge to answer this question.  I have uploaded the WKT for you to find what is the possible reasons

[two_in_koppen.wkt.txt](https://github.com/AtlasOfLivingAustralia/spatial-hub/files/6106010/two_in_koppen.wkt.txt)

**Comment by Tasilee** [comment]
Thanks @Bai and @adam-collins. We somehow need to better align area estimates. I just did an

- Add to map | Area | Gazetteer polygon | 'Equatorial' (Koppen Major Group layer) 
- Tools | Area report - interactive | Equatorial - and got 44,316.81 sqkm
- Export | Area | Equatorial (Shapefile)
- Import | Area | Shapefile (Equatorial.zip)
- Tools | Area report - interactive | Equatorial.zip -> **Locked up!**
- Click (i) on Equatorial.zip and got 107,349.18 sqkm. That is more than double the original report.

So, another error and a significant difference in the areas. If I run Equatorial.zip into QGIS, it says there is a topology error (at one intersect).
