### ISSUE TITLE
Support for smaller (smartphone) screens

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#348]
A user has reported issues when attempting to use the Spatial Portal on an iPhone - the screen cannot be scrolled far enough across to reach the "Next" button when adding a species or spatial layer.

I've seen similar issues on Chrome on an Android phone, where neither "Cancel" or "Next" buttons are visible or reachable, and the map itself cannot be brought into view. Other existing features do appear to work - looking up a species by text, or loading a saved session, function identically on mobile and desktop, so display and navigation are the only visible features lacking at the moment.

The obvious workaround is to use SP on a larger screen, but this is a usability gap as other ALA applications are usable on a small screen. Ideally the SP interface should be modified or adapted to allow full navigation and functionality on smartphones.

**Comment by Tasilee** [comment]
Some years back, I discussed the issue with @adam-collins - at least in relation to iPads. The SP is essentially a research-oriented portal, so I’d say it is unlikely to be resourced to support phone interfaces. IPads (and counterparts), at least in theory, are another matter, as they do have usable screen real-estate and often have good add-on keyboards. I know the differences between huge phones are small pads can be grey, but I think there is a separation. There was an issue for this.
