### ISSUE TITLE
Info and Zoom buttons on layers accessed via ?layers= URL parameter do not work correctly

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#349]
Seems like a minor UI bug.

1. Add a layer to SP, eg. Temperature - Annual mean (Bio01)
2. Pan the map around a bit and click the Zoom icon - view zooms correctly to layer extent
4. Click the Info icon next to the layer in the list
5. Scroll down to "View in spatial portal" and click "Click to view this layer", eg link: https://spatial.ala.org.au/?layers=bioclim_bio1
6. Click the Info icon on the layer in the new view - nothing happens.
7. Click the Zoom icon on the layer - map zooms almost the whole way out.

The behaviour of the Zoom and Info icons is incorrect for spatial layers accessed via the "layers" URL parameter instead of being added to the portal as normal.

Issue discovered during general use, not raised by a user, so no relevant helpdesk ticket.

Screenshot attached shows the effect of clicking Zoom on a layer accessed via the URL parameter.

![bio01 zoomed out](https://user-images.githubusercontent.com/57081387/96515132-816ed300-12b0-11eb-9b55-38fc9bce624b.png)

**Comment by qifeng-bai** [comment]
Since the data object contained in the panel has been updated.
Correct: [
![Screen Shot 2020-11-13 at 2 10 37 pm](https://user-images.githubusercontent.com/31238531/99024256-48c5cf00-25ba-11eb-901e-8aeff3d74649.png)
](url)

Wrong:
![Screen Shot 2020-11-13 at 2 11 04 pm](https://user-images.githubusercontent.com/31238531/99024285-5a0edb80-25ba-11eb-917b-d31c07293ae7.png)

**Comment by qifeng-bai** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/ab75987e42f54c62664aa7ed97734714599996a0

**Comment by adam-collins** [comment]
Wrong nginx settings. Spatial-service did not create the layers in geoserver. Cannot test.
