### ISSUE TITLE
Preset area for "Australia" needs improving

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#351]
When using `Add to map` -> `Species`, the 3rd option `Restrict to an area` has an option for `Australia`. That area ends up being a rectangular polygon that simply surround the continent. See below:

![image](https://user-images.githubusercontent.com/532845/98601483-38e88980-2333-11eb-89d6-c05cdfa635ff.png)

The problem is, it includes part of Indonesia, Timor Leste and PNG.

This should be using a layer for Australia that includes the EEZ for AU plus land areas. 

We don't appear to have such a layer, as the EEC layer only includes marine areas and excludes the land areas of Australia. 

![image](https://user-images.githubusercontent.com/532845/98601995-e3f94300-2333-11eb-8dcf-df1f3c49a0de.png)

This would be consistent with how GBIF defines countries in their data portal.

CC @Tasilee - maybe there was a rationale for this that I've missed?

**Comment by nickdos** [comment]
I think we should be using this layer https://data.gov.au/dataset/ds-dga-a8c72ee4-d0c1-4447-973a-e5d2241b388c/details

**Comment by Tasilee** [comment]
I agree that the rectangle is too simplistic. Defining the 'Australian region' is however complex. Full EEZ yes, External Territories yes, States and Territories yes, Territorial Seas yes.

**Comment by peggynewman** [comment]
I can't seem to get that layer to render on National Map @nickdos but if you go there and search for Australia's Exclusive Economic Zone map service something looking good comes up and includes Antarctica.  
I'll set up the ticket to load a/the layer, but then what needs to happen in spatial and biocache hubs to change the definitions?

**Comment by peggynewman** [comment]
Created https://github.com/AtlasOfLivingAustralia/layers-service/issues/126

**Comment by qifeng-bai** [comment]
@peggynewman  @nickdos  I uploaded Australia EEZ to my dev environment (Spatial Service). However, Biocache returns 0 records. I wonder we also need to load this layer to biocache as well?

**Comment by nickdos** [comment]
@adam-collins I think there is an existing layer that is used in Pipeline for the EEZ boundaries, already? Can you provide details, pls?

**Comment by qifeng-bai** [comment]
Use Australian EEZ as an example
https://github.com/AtlasOfLivingAustralia/spatial-hub/tree/351_preset_area

**Comment by nickdos** [comment]
See https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/84830dd0bc58611b3e9c5bc5c4ca08932456fe27#commitcomment-55170660
