### ISSUE TITLE
Missing attribution to Open Street Map as base map

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#352]
When changing the base map to Satellite, Streets or Hybrid, the correct copyright attribution for Google and/or NASA shows in the bottom right corner under the attribution link for Leaflet:

![SP google nasa copyright](https://user-images.githubusercontent.com/57081387/98609070-a5b65080-2340-11eb-8b2d-3e14bab8cf0a.png)

However the attribution for Open Street Map is missing:

![SP OSM copyright missing](https://user-images.githubusercontent.com/57081387/98609104-b49d0300-2340-11eb-8040-3908ff5f92f2.png)

This should be prioritised as it is as licensing issue.

Reported in helpdesk ticket: https://support.ehelp.edu.au/a/tickets/95757

**Comment by qifeng-bai** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/ab75987e42f54c62664aa7ed97734714599996a0
