### ISSUE TITLE
Create a logger controller

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-hub#362]
Spacial hub need to log events to log server
Currently,  SH send to request to SS logger controller with user id,  SS will try to call CAS to authenticate.  CAS won't work because it needs an interactive call

To fix:
Create a logger controller in SH

![Screen Shot 2020-12-17 at 10 33 34 am](https://user-images.githubusercontent.com/31238531/102419208-71c2ff00-4053-11eb-80bf-0eb258befe35.png)

**Comment by adam-collins** [comment]
Fixing the nginx configuration on the test server fixes this issue. There is no need for creating a proxy to every other ALA webservice.

Sharing session logins between all ALA applications is the preferred solution. We are already doing this elsewhere in the ALA.
