### ISSUE TITLE
Non-linear legend is misrepresenting spatial data

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#365]
Reported in https://support.ehelp.edu.au/a/tickets/98128 and others previously.

Spatial layer data is represented non-linearly at the extremes, making it very easy to misinterpret data without noticing. See the attached screenshot for an example - for a dot point that looks like it should be in the mid-to-high 40s on the scale, it actually reads 3.978 in the data.

The issue in this case was discovered by a user of another site that uses ALA spatial data: https://maps.eatlas.org.au/index.html?z=5&ll=134.42090,-23.38295&l0=ala_ALA%3Ageomacs_gmean,ea_ea-be%3AWorld_Bright-Earth-e-Atlas-basemap&intro=false

Another suggestion previously reported by another user is the ability to reverse the colorisation of the legend - this would help in cases of eg. temperature, if the "low" temperature actually shows as red and "high" as blue.

Possible approaches to mitigate or solve this issue:
- Custom colour ranges, to display effects of multiple layers, or a checkbox to reverse colours
- Showing multiple values in the legend, to better illustrate that it is nonlinear at the extremes
- Some separate way of displaying extreme outliers, or detecting and removing them entirely, so values that are only found in say 1% of regions do not affect the remaining 99%, leaving the legend as linear to range within expected values

![SP nonlinear representation](https://user-images.githubusercontent.com/57081387/104256997-7f439b80-54d0-11eb-933a-75df0def40d1.png)

**Comment by Tasilee** [comment]
Thanks @timhicks-ala. I agree that the colour reversal is warranted with a subset of layers. When the review of layers has been fully implemented, it would be easy to tag those that required reversing. A tick box is an alternative. I don't know which is simpler. 

The scaling we originally settled on reflected equal area but the downside is noted. Using a linear scale is simplest but will also have some issues.

**Comment by qifeng-bai** [comment]
@adam-collins created a PR:  https://github.com/AtlasOfLivingAustralia/spatial-service/pull/161

**Comment by Tasilee** [comment]
Tested (spatial test). I'd suggest that a) the length of the linear legend in the SP's legend area should be the same as the non-linear one and b) that the grey scale is inadequate to show values so a spectrum should be used (similar to the non-linear legend).

**Comment by qifeng-bai** [comment]
@Tasilee I will create another enhancement ticket for your suggestion

**Comment by timhicks-ala** [comment]
Hi @nickdos and @qifeng-bai , to my understanding a black-and-white linear-style scale has been added - is there more to do on this one or can we close it?

**Comment by timhicks-ala** [comment]
Closing as this is done
