### ISSUE TITLE
Missing urls in list after session deleted

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-hub#368]
**Describe the bug**
Urls are missing after a session is deleted

**To Reproduce**
1. Go to 'load'
2. Click on 'delete' button to delete a session
2. See error: urls in the list are missing

**Comment by qifeng-bai** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-hub/pull/364

**Comment by Tasilee** [comment]
Tested (spatial test) and the URLs of the remaining sessions are retained.
