### ISSUE TITLE
Check 'Include absences' and other options when we list records of facets

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-hub#374]
@nickdos Also reported:

Add a species to map but don't select any of three spatially-related options,  always get zero dots.

**Reason**
If no spatially-related options selected, query will build as '-*:*', which return 0 records

**Solution**
Force user to select at  least one option.

___________________________________________________________________________________________________

**Describe the bug**
@Tasilee  reported:
Add to map | Facet | World | Include spatially valid records. 

In the Facet dropdown box, select 'Year' under the --Occurrence'-- category, click on 'Sorted by name' and page to <2> and select "1765" (about 5 records should be mapped). 

The list of facets in the dropdown are a small subset of those available through the Search facets option. 

BROKEN: Only one record mapped. Why?

**Screenshots**
![Screen Shot 2021-03-01 at 4 40 07 pm](https://user-images.githubusercontent.com/31238531/109456471-04990480-7aad-11eb-8733-16949fb4cce4.png)

**Reasons**

In title of  Section 3 : **3. Select facet (counts ignore species options)**

When we click 'Next',  selected 'geospatial_kosher:true' will be added into query
https://biocache-ws-test.ala.org.au/ws/occurrences/search?fq=year1765&fq=geospatial_kosher:true returns 1 record
However, in 'select Facet', we do not apply 'Species Options' in
https://biocache-ws-test.ala.org.au/ws/occurrences/search?fq=year:1765 returns 5 record

**Research**
@adam-collins  mentioned:
`spatially-valid = geospatial_kosher:true`
`spatially-suspect = geospatial_kosher:false`
`spatially-unknown = -geospatial_kosher:*`

'Include spatially-valid records' -> has Spatail data -> geospatial_kosher:true
`https://biocache-ws-test.ala.org.au/ws/occurrences/search?fq=year1765&fq=geospatial_kosher:true` returns 1 record

'Include spatially-unknown records' -> no spatial data -> -geospatial_kosher:* 
`https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=year:1765&fq=-geospatial_kosher:*`  returns 4

**_Based on doc:  https://cwiki.apache.org/confluence/display/solr/NegativeQueryProblems
These queries will not work as expected:
-field1:value1 OR field2:value2_**

If we aim to collect records of  "valid spatial OR  missing spatial data" with this query:
`https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=year:1765&fq=(-geospatial_kosher:* OR geospatial_kosher:true) `
**It will not work**

Instead, we should query data which are not 'suspect' 
`https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=year:1765&fq=-geospatial_kosher:false`

---------------------------

Issue2:
Correct single/plural  and replace 'facet' with 'class/es'

**Comment by qifeng-bai** [comment]
Look through this doc: https://cwiki.apache.org/confluence/display/solr/NegativeQueryProblems
These queries will not work as expected:
-field1:value1 OR field2:value2

**Comment by qifeng-bai** [comment]
PR: https://github.com/AtlasOfLivingAustralia/spatial-hub/pull/376

**Comment by nickdos** [comment]
While testing this, I found trying to the `facet begins with..` option - it just spins and I get no output:

![image](https://user-images.githubusercontent.com/532845/114961970-38898700-9ead-11eb-81dd-b0c1c599aa2b.png)

**Comment by qifeng-bai** [comment]
SP sends a query : https://biocache-ws.ala.org.au/ws/occurrence/facets?facets=year&flimit=10&foffset=0&fsort=count&q=qid:1618538555155&fprefix=17

Get response:

{
message: "Error from server at http://aws-sc2b.ala:8983/solr/biocache: Error from server at http://aws-sc2b.ala:8983/solr/biocache-2021-04-16-09-10_shard1_replica1: facet.prefix is not supported on numeric types",
errorType: "Query syntax invalid"
}

SP needs add an error handler to deal with that

**Comment by nickdos** [comment]
Facet is now showing the expected 1 record in the facets selection table.
