### ISSUE TITLE
AOO/EOO tool - draw polygon then defaults to World instead of my polygon

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#379]
If you choose this tool, then select the "define new area" option", "draw polygon" click next. It allows you to draw the polygon on the map. It then jumps back into the wizard screen. The next screen then has the option for selecting an "area" but it defaults to "world". It should be smart enough to know you've just used the "define new area" tool and to make "My polygon" the selected option on this screen.

![image](https://user-images.githubusercontent.com/532845/110741389-adebb180-8288-11eb-95ab-ed1a60fabf63.png)

**Comment by qifeng-bai** [comment]
Cannot reproduce or has been fixed

**Comment by nickdos** [comment]
Just replicated it in production now - still a bug.

**Comment by nickdos** [comment]
Code reviewed ✅
