### ISSUE TITLE
Display error message when we import handling SHP/KML area  

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-hub#380]
Error message cannot be displayed properly on SP. It is caused by:
1, SP (JS and Grails) do not capture 'statusCode' or error message (including different formats of returning error message)
2, SS discards the error message or does not capture the error message.

**Comment by qifeng-bai** [comment]
Duplicate of #345

**Comment by nickdos** [comment]
I see `Error:undefined` note no space between words. Not sure that is very useful - can the message be more informative?

![image](https://user-images.githubusercontent.com/532845/114507199-207bf280-9c76-11eb-9e70-3cf29a035f98.png)

**Comment by nickdos** [comment]
I now see an error message:

> Unexpected error. Please check logs for more information

I'm not sure this is useful for the user. They don't have access to logs so why tell them that? A better message is one we use on biocache and BIE. 

> An error occurred. Please try again and if the same error occurs, send an email to support@ala.org.au and include the URL to this page, the error message and what steps you performed that triggered this error.
