### ISSUE TITLE
Browser warning: elements with non-unique id attribute 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#383]
There are 2 elements in the DOM with an `id="styles"` attribute (`id` should be unique). This could result in unexpected behaviour if being called via JS in any way. 

![image](https://user-images.githubusercontent.com/532845/111934179-03d81900-8b15-11eb-8d3f-3865215decd3.png)

**Comment by qifeng-bai** [comment]
commits:
https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/d6004f6e47fe9e6bde655ca98ab9a1e343b409eb

**Comment by nickdos** [comment]
Code & fix look good.
