### ISSUE TITLE
Blank "||||" line appears in SP species list

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#387]
Seems to occur in some areas but not others.

To reproduce:
1. Try this saved session with an area around Queanbeyan, NSW: https://spatial.ala.org.au/?ss=1616566285437
2. View area report for that area and click "List" for Number of species
3. The following will show, with one line showing only four pipe characters for a species name (there should be a species name, biodiversity LSID, common name and kingdom/family between these characters):

![pipe character species](https://user-images.githubusercontent.com/57081387/112264559-2c067a00-8cc5-11eb-8f88-07c0ca09cc44.png)

4. Download the species list from the area report, you'll see a matching |||| line with a number of occurrences attached to it:

![pipe character list](https://user-images.githubusercontent.com/57081387/112264951-c5ce2700-8cc5-11eb-9945-ed3cc83087be.png)

There is only one "||||" line in the entire list, so it seems like one genuine species is not being named correctly in the SP area report/species list download.

At the end of the downloaded species list is also a collection of species identified only by their common name - these will be records with an unmatched common name specified, which is probably to be expected:

![pipe character common](https://user-images.githubusercontent.com/57081387/112265171-22c9dd00-8cc6-11eb-9f27-aef65d4a2e63.png)

**Comment by qifeng-bai** [comment]
Cannot reproduce any more

**Comment by timhicks-ala** [comment]
Confirmed - looks like another fix/change along the way has fixed this as well.
