### ISSUE TITLE
Previous user saved sessions are missing in prod

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#388]
After a recent change, viewing the saved sessions (using the "load" menu item) on SP shows older entries without a link (URL column). Therefore users are not able to reload previously saved sessions (saved sessions created since last version are OK). See screenshot:

![image](https://user-images.githubusercontent.com/532845/112267437-8f92a680-8cc9-11eb-899c-34e86d196c1d.png)

Adam thought the last release had a change relating to this function. Although we did delete some dirs in `/data` so can't completely rule this out. See [Slack comment](https://atlaslivingaustralia.slack.com/archives/CCSTT3GCR/p1616043010007300).

**Comment by qifeng-bai** [comment]
It is designed to do so.   URL in last version was calculated on runtime, Adam and I found there are some issues on this solution. Restoring session does not work properly intermittently, reported in  https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/245 

In current version, URL is generated and stored when we save a session. 

@nickdos we can support calculating the url on fly as well, however,  this url is not guaranteed to work all the time.

**Comment by nickdos** [comment]
@qifeng-bai - if you can support the old way for "legacy" saved data, this is preferable.

**Comment by qifeng-bai** [comment]
PR: https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/c9e78ac4d29befb6f51dd1087b6826b2e436db6d

**Comment by nickdos** [comment]
Code reviewed ✅

**Comment by nickdos** [comment]
Can't test actual fix as my account on test did not have any old saved data. I did test adding new data and it works as expected.
