### ISSUE TITLE
Threatened Species list does not display in Area Report

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#389]
To reproduce:
1. Create an Area in SP
2. View the Area Report for that area
3. Click the List button next to Invasive Species, Migratory species - EPBC, or Australian Iconic Species - these lists appear as expected.
4. Click the List button next to Threatened Species - a popup appears with the correct title but no data.
5. Clicking "View Records" and then downloading a species checklist via biocache is also impossible as the query generated in biocache is incorrect, pulling in millions of records and thousands of species, even if only a handful of threatened species are listed in the area report.

Reported in https://support.ehelp.edu.au/a/tickets/103579

![blank threatened species list](https://user-images.githubusercontent.com/57081387/113233149-4a363080-92ea-11eb-8bc6-e9ba32e63b28.png)

**Comment by timhicks-ala** [comment]
Additionally reported in https://support.ehelp.edu.au/a/tickets/106841

**Comment by qifeng-bai** [comment]
It has been fixed.
