### ISSUE TITLE
Uploading a species list - default `make private` to be `true`

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#394]
E.g. see screenshot

![image](https://user-images.githubusercontent.com/532845/115644074-47ff4900-a361-11eb-9a5d-b1c8b3aa1e05.png)

The `Make private` tickbox should be ticked (on) by default - currently its off by default.

This will bring it into line with the SpeciesList app, which [also made this change](https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/120).

**Comment by Tasilee** [comment]
I am sorry but I have to protest yet again. I see this as a classic 'developers' vs 'user perspective'. 

1. There are a lot of lists yes, but we need a mechanism of filtering (which is ok with sorting and 'Refine lists' options).
2. We need an automated + manual clear out of temporary and old lists (and we need to publicize the strategy). Yes, this is 'work' but it is necessary anyway.
3. By default, the ALA is 'OPEN', FOSS and all that and to default to PRIVATE cuts right across this openness. I am philosophically (strongly) opposed to hiding lists (and most things unless it is seriously necessary - as you can set it to Private anyway, just not by default please)

This is a similar issue to my disagreement with Dave over exposing all data. I strongly urged that we must expose all, AND provide a clear mechanism of filtering. I believe a lot of Miles' work has now done this for biocache and we have had that a tad longer in the SP.

**Comment by nickdos** [comment]
Hold off on working on this issue until Architecture & Operations groups has agreed on it.

**Comment by Tasilee** [comment]
Grrrrr
