### ISSUE TITLE
Spatial options not displayed on AOO/EOO wizard UI

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#403]
When running an AOO/EOO calculation, the modal shows the following:

![image](https://user-images.githubusercontent.com/532845/121981833-c3193480-cdd1-11eb-82cf-2e203a08a5fe.png)

~~The warning line `Minimum one spatially related option is required! See this support article for more information` should not be displayed here, as there are no **spatially related options** on this form.~~

Update: the spatial options are not being displayed above the warning for some reason. Seems to be for URLs that come via biocache, e.g. https://spatial.ala.org.au/?q=lsid:https:%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2920976&disableAllQualityFilters=true

**Comment by nickdos** [comment]
Seems to occur when using a link from biocache, such as 

https://spatial.ala.org.au/?q=lsid:https:%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2920976&disableAllQualityFilters=true

When using new session, the spatial options are displayed.

**Comment by qifeng-bai** [comment]
Fixed. One line code change:  https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/2ed9c4fc18d51a48970f6bbe6d4671a97f9ece3f

**Comment by nickdos** [comment]
Thanks @qifeng-bai - I just looked at change and its trivial so code review done ✅
