### ISSUE TITLE
"View interactive map" does not work for Thryptomene sp. Leinster

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#408]
1. View species page for this species: https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2904210
2. Click "View interactive map". SP loads with this URL: https://spatial.ala.org.au/?q=lsid:https:%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2904210

Note that no occurrence records are shown on the SP map, and no species entry is shown on the left.

All occurrence records are visible in Biocache, with a total of 24 (23 are hidden by the default data quality profile): https://biocache.ala.org.au/occurrences/search?q=lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2904210#tab_mapView

And that one record, or all 24, appear in SP if you click "View in spatial portal" from Biocache.

"View interactive map" works fine with species with more occurrence records, so it's something to do with this particular species and how its records are treated by the system. Possibly SP is taking the default DQ profile and narrowing down to one record, and then that one has an issue when being read by SP - Doug points out the species name includes an ampersand symbol, so it could be failing to properly encode this character.

Issue originally raised in https://support.ehelp.edu.au/a/tickets/111001

**Comment by qifeng-bai** [comment]
Cannot reproduce this issue in the current release
