### ISSUE TITLE
Export points: Add "All added species" option

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#414]
A user recently raised a case of trying to run the Export Points tool for multiple species. They had added about eight individual species to their session, and when attempting to export points, they selected the "All species" option, assuming this would include all eight species of interest.

The actual outcome was to add all species in the ALA, leading to an immediate (and confusing) "Download skipped" message.

The suggestion is to add an option to the Export Points tool, which allows the user to run it on all species that have been added in a session, rather than running the analysis on each species one by one, and to carefully adjust the wording of both it and the original "All species" option to avoid future confusion.

**Comment by Tasilee** [comment]
Good idea.
