### ISSUE TITLE
Dialog hangs when adding a species with no occurrences in an area

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#415]
1. Add an area in SP (eg. a small rectangle in SA)
2. Add a species to that area that has no occurrences in the area (eg. Casuarius casuarius)
3. Dialog shows "No occurrences mapped for this layer and applied filters." as expected.

![image](https://user-images.githubusercontent.com/57081387/126746016-f56ee1f1-0b2e-40f5-963c-6b36c94aa8fb.png)

4. Click OK on that box. The "Add a species layer to the map" box remains, with an unavailable "Next >" button. You can only click Cancel on this, but you shouldn't need to if adding a species has failed.

![image](https://user-images.githubusercontent.com/57081387/126746142-ff972509-38c8-4968-8225-2af17195a849.png)

5. "Casuarius casuarius (My Rectangle)" is still added to the list on the left as a species, despite containing zero occurrences.

![image](https://user-images.githubusercontent.com/57081387/126746156-6524d703-817e-44e5-8c63-627d60ac7002.png)

Expected behaviour:
- Where adding a species to an area fails due to no occurrences being found, all dialog boxes should be dismissed when clicking "OK" on the "No occurrences mapped..." box.
- An empty species entry should not be added to Spatial if no occurrences were found.

**Comment by Tasilee** [comment]
Fully agree. I have had the same issue a number of times.
