### ISSUE TITLE
Cannot create species list - dialog does not progress

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#416]
Raised in https://support.ehelp.edu.au/a/tickets/112143
Additionally raised in https://support.ehelp.edu.au/a/tickets/118351, https://support.ehelp.edu.au/a/tickets/119760, https://support.ehelp.edu.au/a/tickets/120297

1. Add species -> Create new species list
2. Add a couple of species to the list, click Add.
3. Type anything you like for the species list name and description, clicking the Next button does nothing - the process hangs at this point.

Note also that the default list type is "Other", and that "Spatial portal defined" does not appear in the list of options here, whereas it does when creating a list on lists.ala.org.au itself.

![image](https://user-images.githubusercontent.com/57081387/127080505-85e42810-0be2-44ba-9bd2-629f1d00922c.png)

**Comment by qifeng-bai** [comment]
Link to: https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/416

**Comment by qifeng-bai** [comment]
PR:  https://github.com/AtlasOfLivingAustralia/spatial-hub/pull/418

**Comment by timhicks-ala** [comment]
Closing as this appears to be fixed.
