### ISSUE TITLE
Cannot find some existing species lists from within Spatial

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#417]
These two lists are practically identical - same 3 items, same type ("Other"), neither set to private:

https://lists.ala.org.au/speciesListItem/list/dr17667 - "Tim's kangaroo list"
https://lists.ala.org.au/speciesListItem/list/dr17670 - "A short list of kangaroos"

However, only one of these lists can be found when adding an existing species list within SP:

![image](https://user-images.githubusercontent.com/57081387/127081434-85a3b543-4a74-4c74-ba1d-3cb4250b9fd3.png)

So there may be an issue with searching for and displaying certain lists from within Spatial - possibly the apostrophe in the first list's title is the issue.

This issue was not reported via helpdesk, however it may be invisibly affecting users searching for a list that happens to contain unusual characters.

**Comment by qifeng-bai** [comment]
Link to : https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/417
