### ISSUE TITLE
New tool tabulation - species list x contextual classes

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#42]
Reading http://onlinelibrary.wiley.com/doi/10.1111/aec.12487/abstract where the authors exported the number of vegetation species by IBRA regions, it is apparent that this would be a long manual process currently in the ALA/SP.

If we could take a species list and any single contextual layer (e.g., IBRA 7) and then produce a table that contained for each IBRA area

1. Area
2. Number of occurrences
3. Number of species (of the species list species)
4. ...

That would very very useful!

**Comment by Tasilee** [comment]
...slept on it and figure species selection should follow current options (single/multiple/list or a lifeform).

**Comment by Tasilee** [comment]
Generalization if the selected layer was environmental - the output would be a histogram. This tool would be very generic (widely applicable).

**Comment by Tasilee** [comment]
Minor issues

1. Name of tool should be "Tabulation - 1D" and the current "Tabulate" renamed to "Tabulate - 2D"
1. When first run, no pop-up table is displayed and the download file is called "SpeciesByLayer.zip". Subsequent runs in the same session display the pop-up table and the download is called "download.zip".

**Comment by nickdos** [comment]
Needs ansible change for config to show option in tools menu.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/commit/8056664e484e3927cc9f6d7d14e20d3a4eee00ed
