### ISSUE TITLE
Species common name not being recognised

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#425]
@elywallis raised this bug when testing indigenouse names. 

> You can search using one of the already uploaded Kamilaroi names in both the BIE and the Biocache (for eg try Dhinawan = emu) but it doesn't work in the spatial portal.

I can confirm "Dhinawan" fails to work on the Add to map -> species page:

![image](https://user-images.githubusercontent.com/532845/137040648-e7212320-0f1e-437a-8716-253028639ece.png)

The autocomplete does not recognise the name and thus the "next" button remains inactive. 

The BIE recognises it as "Emu" so not sure if that is the best UX...

![image](https://user-images.githubusercontent.com/532845/137040780-0739cc79-63a3-48e1-a7c4-30949744d559.png)

**Comment by qifeng-bai** [comment]
https://biocache-ws.ala.org.au/ws/autocomplete/search?q=Dhinawan  returns empty

**Comment by nickdos** [comment]
Issue moved to [AtlasOfLivingAustralia/biocache-service #715](https://github.com/AtlasOfLivingAustralia/biocache-service/issues/715) via [**ZenHub**](https://www.zenhub.com/)
