### ISSUE TITLE
Cannot add large species lists to an area in SP

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#436]
Adding large lists of species to an area in Spatial seems to fail by hanging/perpetually waiting. An example of a list that fails is the GRIIS Australia list, at ~3800 species: https://lists.ala.org.au/speciesListItem/list/dr9884

Adding a smaller list (~2100 - Advisory List of Rare or THreatened Plants in Victoria 2014) seems to complete, and the dialog box to add species disappears, but no occurrence dots appear on the map.

This seems to occur with an area of any size - I get the same results with a shapefile supplied by a user, and also a tiny city-sized polygon. The GRIIS list was the one attempted by the user.

The practical upper limit for adding a species list to SP seems to be at or below 1,000 species in a single list.

Issue reported in https://support.ehelp.edu.au/a/tickets/126609

**Comment by timhicks-ala** [comment]
Also reported in https://support.ehelp.edu.au/a/tickets/146232 - user attempting to use a species list with 3,700 entries.

**Comment by patkyn** [comment]
Tested and passed
