### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#44]
spatial.ala.org.au is responding on port 443 to HTTPS requests. However, the application contains many references back to insecure HTTP resources that are failing. These need to be updated where possible to reference HTTPS.

Many of the base resources, www.ala.org.au, bie.ala.org.au, biocache.ala.org.au, lists.ala.org.au, openstreetmap.org, and google.com fully support HTTPS, but there are a few ALA servers such as logger, spatial-test and collections that do not have it available yet.

**Comment by adam-collins** [comment]
All http/https URLs should be in config.

Browser http/https crossing needs detection and pass through the proxy service. This includes external WMS layers if/when browsers also block images.

AtlasOfLivingAustralia/spatial-service updates are also required and postgres layersdb.layers table contains URLs.
