### ISSUE TITLE
Handle occurrenceStatus="absent" in Add to Map | Species

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#46]
While we remove "absence" records from analytical tools, we display records with occurrenceStatus="absent" as "present" - which is a problem. 

Suggestion (thanks Adam): Add check box on Add to map | Species similar to the "Include spatially-valid records" as in "Include occurrenceStatus=absent records".

Related (separate issue): We MUST (!) replace "Presence/Absence" as facet name with the proper Darwin Core term "occurrenceStatus".

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/2ecaa453a973c94ac674eabd370a46ac33c40184

**Comment by adam-collins** [comment]
Make occurrence_status_s=true fq configurable.
