### ISSUE TITLE
Pagination not displaying for some layers, on some browsers

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/spatial-hub#464]
This example refers to the IBRA7 subregions layer.

After adding the layer, Firefox, Edge and Safari seem to be displaying a full list of subregions and the pagination buttons to navigate through. 
However, this is not working consistently on Chrome. 
Note also that for the displays without pagination I can still search for a subregion and it will be returned.

The issue seems to be with particular layers, or just IBRA7 Subregions, as IBRA7 Regions works ok. 

No pagination (Chrome):
<img width="1564" alt="IBRA7-chrome-no-pagination" src="https://github.com/AtlasOfLivingAustralia/spatial-hub/assets/90439797/fead05c4-e612-43d4-8e0a-c3b56b1df4bc">

Functioning, with pagination (Firefox, Safari, Edge):
<img width="1342" alt="IBRA7-subregions" src="https://github.com/AtlasOfLivingAustralia/spatial-hub/assets/90439797/3108865f-22ad-4336-80ef-12590db990d3">

raised by user: https://support.ehelp.edu.au/a/tickets/190947

**Comment by adam-collins** [comment]
For an unknown reason `ibra7_subregions` was missing from geoserver. This reduced the scrollable area because the legend image was missing.

Fixed by adding it back.

There was an alternative, grab the resize tool by hovering over the legend heading and make it bigger.

**Comment by kylie-m** [comment]
Thanks Adam, it's working well for me now
