### ISSUE TITLE
Better webservices for integration

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#48]
Roughly thinking of this workflow from an external site:
- create a new session. http://spatial-hub/set (sessionId, apiKey, map settings including layers)
- open and edit a session. Include a button for returning. http://spatial-hub?ss=sessionId&returnUrl=somewhere&returnText=instructions
- fetch session settings that may have changed. http://spatial-hub/get (sessionId, apiKey) 
- add/remove layers with​​​ set (get(edited sessionId) +/- layer) to the same session or new session
- open the same/new session​, or if still open notify and accept​ the changes.

Not needing the apiKey would be nice.

**Comment by Tasilee** [comment]
Thanks Adam. We need to ensure we are meeting user needs, and a July 3 (and I think good) example from Beth Crace (CDU) will help-

"First type... I have a list of about 3000 data deficient taxa and for each I would like to know the number of records (in Australia, not all of ALA), the year of the most recent record, family name and (ideally) the AOO or EOO."

I think this is indicative of the type of summary measures we must support. Spatial intersection with our gross summary layers (occurrence density, species richness, endemicity, Shannon diversity) would be expedient. But, we need to support a web service that also picks up results from Points to Grid and AOO/EOO.

"Second type of data...is a set of occurrence records for our list of 3000 data deficient taxa. Ideally it would only contain data with a particular spatial precision - is there a way to filter the location records before exporting? It seems that this might be a routine use of the ALA database - is there some supporting documentation?"

This is covered now but the suggested Tool (https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/47) would help a lot.

"Third type of data... we would like to plot the location records for data deficient Australian plants, calculate a record density by grid cell and then scale it by collection effort (which would be generated by using all plant collection records, calculating a point density grid of same grain and extent)."

I think this would be covered by a web service on Point to Grid results? We need a mechanism of generating a density layer on one suite of taxa and then tapping that layer (spatial intersection)?
