### ISSUE TITLE
Double gridding Tool - Occupancy Grids

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-hub#49]
Donald Hobern demonstrated some GBIF scripts that may prove handy for comparing aggregated data across the three dimensions of name, space and time. Certainly relevant to EBVs and SoE. It goes like this

1. Supply a taxa (usually a genus or higher)
2. Supply a primary grid size (e.g., 0.1 degree or 10km)
3. Supply s secondary grid size (e.g., 1 degree or 100km)
4. Supply a temporal bin range (e.g., 10 years)

5. Generate a points to grid using the primary grid size on the taxa

6. Calculate the new layers at the secondary grid size for each time slice
    a. Number of non-null primary grid cells (bins)
    b. Number of species in bins
    c. Number of occurrences in bins
    d. For each species present: Number of occurrences for species x in bins

An example of the type of data produced-

latitudeRange | longitudeRange | timePeriod | speciescount | bincount | occurrenceount | Streptopelia roseogrisea   (Sundevall, 1857) | Streptopelia mayeri (Prevost,   1843) ...
-- | -- | -- | -- | -- | -- | -- | --
-74.0,-73.0 | +030.0,+031.0 | 2000-2017 | 1 | 1 | 2 |   |  
-44.0,-43.0 | +146.0,+147.0 | 2000-2017 | 1 | 1 | 1 |   |  
-44.0,-43.0 | +147.0,+148.0 | 2000-2017 | 1 | 5 | 5 |   |  
-44.0,-43.0 | +172.0,+173.0 | 2000-2017 | 1 | 29 | 31 | 29 |  
-43.0,-42.0 | +147.0,+148.0 | 1900-1969 | 1 | 3 | 3 |   |  
-43.0,-42.0 | +147.0,+148.0 | 1970-1999 | 1 | 9 | 9 |   |  
-43.0,-42.0 | +147.0,+148.0 | 2000-2017 | 1 | 545 | 606 |   |  

The double gridding removes much of the point-sampling bias and aggregates the data to a level where comparisons across name, space and time should be useful.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/blob/develop/src/main/groovy/au/org/ala/spatial/process/DoubleGridding.groovy

**Comment by qifeng-bai** [comment]
@adam-collins   GET http://devt.ala.org.au:8087/spApp/DoubleGriddingContent.htm 404
DoubleGriddingContent.htm is not committed into git yet

**Comment by qifeng-bai** [comment]
Result has been correctly generated in SS and data  was correctly stored on server. However, downloaded data on client seem incorrect

![image](https://user-images.githubusercontent.com/31238531/103855059-ee527600-5105-11eb-9e00-28674246fe9f.png)

**Comment by qifeng-bai** [comment]
I have added a test for this case:
https://github.com/AtlasOfLivingAustralia/spatial-service/blob/49_double_grid/src/test/groovy/au/org/ala/spatial/util/SimpleRegionSpec.groovy


Succeed on checking a point in SimpleShapeFile.parseWKT("POLYGON((-180 **-89**,180 -89,180 89,-180 89,-180 -89))");
but failed on   SimpleShapeFile.parseWKT("POLYGON((-180 **-90**,180 -90,180 90,-180 90,-180 -90))");

**Comment by qifeng-bai** [comment]
@adam-collins points out we need to use 179.9999 89.9999

**Comment by qifeng-bai** [comment]
@Tasilee  I will create a  new ticket for this improvement.
