### ISSUE TITLE
Migrate aws spatial-test to nectar-spatial-staging

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#53]
Incomplete migration.

Resolve gdal/postgres lib conflict.

**Comment by ansell** [comment]
Can we rename "nectar-spatial-test" to "nectar-spatial-staging" or similar to recognise its purpose in being the data staging location rather than just a test server? The current AWS "spatial-test" naming has confused people who are not aware of its purpose in the spatial layer loading pipeline.

**Comment by matthewandrews** [comment]
Happy to rename it. Does this mean we need a separate spatial test somewhere?

(I'm intending to shut aws-spatial-test down once the migration is complete; when the new version of spatial is ready we'll have spatial prod in AWS.)
