### ISSUE TITLE
Hovering on the map shows field values for removed layers

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#64]
After adding a layer, and then removing it and adding another layer, hovering seems to show field values for both the first and second layers.

In the screenshot below, I added PSMA Commonwealth Electoral Boundaries (2016), then deleted it and added PSMA State Electoral Boundaries (2016). Both values then showed up when hovering.

![screen shot 2018-03-26 at 4 00 58 pm](https://user-images.githubusercontent.com/82365/37887692-ed707530-310e-11e8-8d39-734740239386.png)

**Comment by adam-collins** [comment]
refer to #69
