### ISSUE TITLE
sandbox points upload not working

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#70]

**Comment by adam-collins** [comment]
To be compatible with the current sandbox, include origin in the CORS header on sandbox.

<IfModule mod_headers.c>
   SetEnvIfNoCase Origin ".*" DOMAIN=$0
   Header set Access-Control-Allow-Origin %{DOMAIN}e env=DOMAIN
</IfModule>

**Comment by Tasilee** [comment]
Seems ok to me.
