### ISSUE TITLE
species lists not working

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#73]
Errors with species lists are more easily encountered after the namesindex change. 

A fix is on the biocache-service master and 2.x branch. 
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/71fe2a2630fba662af94e3386641f9229306d627

**Comment by ansell** [comment]
Given you cherry-picked it back to the master branch, is this issue urgent enough to require a new deployment to the current biocache production servers or can it wait for biocache-clustered to be released?
