### ISSUE TITLE
Make default layer point size and opacity configurable.

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#75]
Change default point size from 10 to 15.

Add a checkbox to include point outlines. See ala-hub map for an example.

**Comment by qifeng-bai** [comment]
SLD on staging has been implemented.
We can use   &env=size:36;opacity:0.9 .  to pass variables in to geoservet

For example:
https://nectar-spatial-staging.ala.org.au/geoserver/ALA/wms?service=WMS&version=1.1.0&request=GetMap&layers=ALA:Points&styles=&bbox=-180.0,-90.0,180.0,90.0&width=768&height=384&srs=EPSG:4326&format=application/openlayers&viewparams=s:6503176&env=size:36;opacity:0.9

**Comment by Tasilee** [comment]
Seems fine to me.
