### ISSUE TITLE
Import | Species list is not opening

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#87]
The menu button "Import | Species List" should open the same screen as "Add to Map | Species | Create species list". It is not working.

When the user species list is created, the layer should be mapped immediately.

**Comment by qifeng-bai** [comment]
Bugs: 

createSpeciesListCtrl.js line 137

BiocacheService.newLayer(q, undefined, q.name).then(function (data) {

Complaints 'q' is not defined. 

The possible related to this variable is line 132: $scope.selectedQ = {q: [listIds]

Should 'q'  be $scope.selectedQ.q,

**Comment by adam-collins** [comment]
use $scope.selectedQ as q
use $scope.selectedQ.name as name

**Comment by qifeng-bai** [comment]
Already done that, but it brings another problem. We can have a discussion on standup

[cid:image001.png@01D38FB2.5738FEA0]



Qifeng Bai - Mcomp
Software developer, Atlas of Living Australia National Collections & Marine Infrastructure, CSIRO | Clunies Ross Street, Acton ACT 2601 |  GPO Box 1700, Canberra  ACT  2601
Phone: +61 2 6246 5704 | Fax: +61 2 6426 4264
Qifeng.bai@csiro.au<mailto:Qifeng.bai@csiro.au>
