### ISSUE TITLE
Import | Area displays too many options

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#88]
The menu button "Import | Area" should only display the options "Import shapefile" and "Import KML".

**Comment by qifeng-bai** [comment]
+## No RegExp creation with literal notation
+
+You can't create regular expressions from within AngularJS expressions. This is to avoid complex
+model transformation logic inside templates. Such logic is better placed in a controller or in a dedicated
+filter where it can be tested properly.

https://github.com/angular/angular.js/commit/8b775a0d58f0131a4488ee225204c11b345ce311
