### ISSUE TITLE
Tools | Calculate AOO and EOO

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#91]
Calculate AOO and EOO is producing an empty download file.

It should 
1. display the metadata html
2. add a layer to the map
3. download a zip of containing the metadata html and layer added to the map

**Comment by Tasilee** [comment]
Point 2 above - It should add TWO layers to the map, the Area of Occupancy (AOO) filled grid and also the Extent of Occurrence (EOO) convex hull.

Point 3 - We don't need to automatically Export the AOO and EOO layers as users can do that through Export if needed.
